/* Generated By:JavaCC: Do not edit this line. SQLConstants.java */
package org.lared.desinventar.dbase;

public interface SQLConstants {

  int EOF = 0;
  int SELECT = 5;
  int UPDATE = 6;
  int INSERT = 7;
  int WHERE = 8;
  int FROM = 9;
  int INTO = 10;
  int VALUES = 11;
  int AS = 12;
  int SET = 13;
  int NULL = 14;
  int LIKE = 15;
  int ALL = 16;
  int DISTINCT = 17;
  int DISTINCTROW = 18;
  int TOP = 19;
  int PERCENT = 20;
  int GROUP = 21;
  int BY = 22;
  int HAVING = 23;
  int ORDER = 24;
  int ASC = 25;
  int DESC = 26;
  int COMPUTE = 27;
  int FOR = 28;
  int XDEFAULT = 29;
  int CREATE = 30;
  int VIEW = 31;
  int DROP = 32;
  int TABLE = 33;
  int INDEX = 34;
  int DELETE = 35;
  int DATABASE = 36;
  int ALTER = 37;
  int WITH = 38;
  int UNIQUE = 39;
  int PRIMARY = 40;
  int ADD = 41;
  int COLUMN = 42;
  int CONSTRAINT = 43;
  int KEY = 44;
  int REFERENCES = 45;
  int FOREIGN = 46;
  int NOT = 47;
  int AND = 48;
  int OR = 49;
  int LPAREN = 50;
  int RPAREN = 51;
  int COMMA = 52;
  int NE = 53;
  int LE = 54;
  int GE = 55;
  int GT = 56;
  int LT = 57;
  int EQ = 58;
  int STAR = 59;
  int LITERAL = 60;
  int IDENTIFIER = 61;
  int LETTER = 62;
  int DIGIT = 63;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"SELECT\"",
    "\"UPDATE\"",
    "\"INSERT\"",
    "\"WHERE\"",
    "\"FROM\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"AS\"",
    "\"SET\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"ALL\"",
    "\"DISTINCT\"",
    "\"DISTINCTROW\"",
    "\"TOP\"",
    "\"PERCENT\"",
    "\"GROUP\"",
    "\"BY\"",
    "\"HAVING\"",
    "\"ORDER\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"COMPUTE\"",
    "\"FOR\"",
    "\"DEFAULT\"",
    "\"CREATE\"",
    "\"VIEW\"",
    "\"DROP\"",
    "\"TABLE\"",
    "\"INDEX\"",
    "\"DELETE\"",
    "\"DATABASE\"",
    "\"ALTER\"",
    "\"WITH\"",
    "\"UNIQUE\"",
    "\"PRIMARY\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"CONSTRAINT\"",
    "\"KEY\"",
    "\"REFERENCES\"",
    "\"FOREIGN\"",
    "\"NOT\"",
    "\"AND\"",
    "\"OR\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"*\"",
    "<LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
