Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (1,'INUNDACION','FLOOD','Desbordamiento de aguas, lento o súbito.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (2,'DESLIZAMIENTO','LANDSLIDE','Todo movimiento de masa en la superficie terrestre.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (3,'AVENIDA','FLASH FLOOD','Avenida torrencial, avalancha');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (4,'LLUVIAS','RAINS','Aguacero, chaparrón, chubasco, diluvio.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (5,'VENDAVAL','WINDSTORM','Vientos fuertes. Temporal, ventisca, borrasca.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (6,'TEMPESTAD','STORM','Lluvia con vientos fuertes y descargas eléctricas.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (7,'MAREJADA','COASTAL FLOODING','Llegada extraordinaria de olas al litoral (no Tsunami)');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (8,'SISMO','EARTHQUAKE','Movimiento de la corteza terrestre. Temblor, terremoto.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (9,'HURACAN','CYCLONE','Ciclón, huracán, tifón, tormenta tropical.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (10,'SEDIMENTACION','SEDIMENTATION','Depositación de material sólido por erosión, colmatación.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (11,'HELADA','FROST','Disminución de la temperatura hasta el punto de congelación.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (12,'GRANIZADA','HAILSTORM','Precipitación de granizo.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (13,'SEQUIA','DROUGHT','Temporada seca.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (14,'LITORAL','COASTAL EROSION','Variación de la línea costera.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (15,'ALUVION','ALLUVION','Avenida torrencial en regiones o cauces secos. Huaico.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (16,'ALUD','AVALANCHE','Desprendimiento de masas de hielo y/o nieve.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (17,'TSUNAMI','TSUNAMI','Maremoto. Grandes olas causadas por movimientos en el fondo del mar.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (18,'LICUACION','LIQUEFACTION','Pérdida momentánea de la capacidad portante de los suelos.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (20,'INCENDIO','FIRE','Incendio urbano, rural, industrial (no forestal).');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (21,'FORESTAL','FOREST FIRE','Incendio forestal, quema.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (22,'EXPLOSION','EXPLOSION','Explosión de cualquier tipo (excluye actos terroristas).');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (23,'ESCAPE','LEAK','Escape de sustancias tóxicas líquidas, sólidas o gaseosas.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (24,'ESTRUCTURA','STRUCTURAL COLLAPSE','Daño o colapso de cualquier tipo de estructura.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (25,'PANICO','PANIC','Pánico o histeria colectiva en concentraciones masivas.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (26,'EPIDEMIA','EPIDEMIC','Enfermedad que ataca en una zona a numerosos individuos');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (27,'PLAGA','PLAGUE','Proliferación de bichos.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (28,'ACCIDENTE','ACCIDENT','De transporte vehicular férreo, naviero o de aviación');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (29,'OTROS','OTHER','Otro tipo no incluido en la lista predefinida.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (30,'BIOLOGICO','BIOLOGICAL','Mortandad o migración de especies biológicas');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (31,'ERUPCION','ERUPTION','Erupción volcánica. Incluye emisión de gases, cenizas, piedras, etc.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (32,'CONTAMINACION','CONTAMINATION','Contaminación ambiental, hídrica o en suelos.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (33,'TORMENTA E.','THUNDERSTORM','Concentración de descargas eléctricas en la atmósfera.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (34,'NEVADA','SNOWSTORM','Caida y acumulación de nieve.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (35,'OLA DE CALOR','HEAT WAVE','Aumento de la temperatura media atmosférica.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (36,'TORNADO','TORNADO','Vientos fuertes en remolino y forma de embudo que tocan la tierra.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (37,'NEBLINA','FOG','Masas de nubes que descienden hasta la superficie terrestre.');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (38,'INTOXICACION','INTOXICATION','Envenamiento humano');
Insert into EVENTOS (SERIAL,NOMBRE,NOMBRE_EN,DESCRIPCION) values (39,'OLA DE FRIO','COLD WAVE','Envenamiento humano');

Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Lluvias','Rain');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Inundación','Flood');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Deslizamiento','Landslide');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Falla','Fault');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Tala','Deforestation');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Comportamiento','H. Behaviour');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Error humano','Error');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Diseño','Design');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('El Niño','El Niño');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Otra causa','Other cause');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Cond. Atmos.','Cond.Atmosph.');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Contaminación','Contamination');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Cortocircuito','Shortcircuit');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Depresión tropi','Trop.Depresion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Desbordamiento','Overflow');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Deterioro','Deterioration');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Desconocida','Unknown');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('La Niña','La Niña');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Erosión','Erosion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Erupción','Eruption');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Escape','Leak');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Explosión','Explosion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Inversión térmica','Thermal inversion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Localización','Location');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Neblina','Fog');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Negligencia','Negligence');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Plaga','Plague');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Sequía','Drought');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Sismo','Earthquake');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Sobreexplot.','Overexploit');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Tempestad','Storm');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Vendaval','Windstorm');

