insert into eventos (serial,nombre,nombre_en,descripcion) values (28,'ACCIDENT','ACCIDENT','De transporte vehicular férreo, naviero o de aviación');
insert into eventos (serial,nombre,nombre_en,descripcion) values (15,'ALUVION','ALLUVION','Avenida torrencial en regiones o cauces secos. Huaico.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (29,'AUTRES','OTHER','Otro tipo no incluido en la lista predefinida.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (16,'AVALANCHE','AVALANCHE','Desprendimiento de masas de hielo y/o nieve.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (30,'BIOLOGIQUE','BIOLOGICAL','Mortandad o migración de especies biológicas');
insert into eventos (serial,nombre,nombre_en,descripcion) values (35,'CANICULE','HEAT WAVE','Aumento de la temperatura media atmosférica.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (9,'CICLON','CYCLONE','Ciclón, huracán, tifón, tormenta tropical.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (14,'L'ÉROSION CÔTIÈRE','COASTAL EROSION','Variación de la línea costera.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (26,'ÉPIDÉMIE','EPIDEMIC','Enfermedad que ataca en una zona a numerosos individuos');
insert into eventos (serial,nombre,nombre_en,descripcion) values (31,'ÉRUPTION','ERUPTION','Erupción volcánica. Incluye emisión de gases, cenizas, piedras, etc.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (23,'ESCAPE','LEAK','Escape de sustancias tóxicas líquidas, sólidas o gaseosas.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (22,'EXPLOSION','EXPLOSION','Explosión de cualquier tipo (excluye actos terroristas).');
insert into eventos (serial,nombre,nombre_en,descripcion) values (37,'BRUME DE BROUILLARD','FOG','Masas de nubes que descienden hasta la superficie terrestre.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (33,'FOUDRE','THUNDERSTORM','Concentración de descargas eléctricas en la atmósfera.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (11,'GEL','FROST','Disminución de la temperatura hasta el punto de congelación.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (2,'GLISSEMENT DE TERRAIN','LANDSLIDE','Todo movimiento de masa en la superficie terrestre.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (12,'GRELE','HAILSTORM','Precipitación de granizo.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (7,'HAUTE MAREE','COASTAL FLOOD','Great sea waves braking on the litoral (excludes tsunami).');
insert into eventos (serial,nombre,nombre_en,descripcion) values (20,'INCENDIE','FIRE','Incendio urbano, rural, industrial (no forestal).');
insert into eventos (serial,nombre,nombre_en,descripcion) values (21,'INCENDIE DE FORÊT','FOREST FIRE','Incendio forestal, quema.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (1,'INONDATION','FLOOD','Desbordamiento de aguas, lento o súbito.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (38,'INTOXICATION','INTOXICATION','Envenamiento humano');
insert into eventos (serial,nombre,nombre_en,descripcion) values (18,'LICUACION','LIQUEFACTION','Pérdida momentánea de la capacidad portante de los suelos.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (34,'NEIGE','SNOWSTORM','Caida y acumulación de nieve.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (25,'PANIQUE','PANIC','Pánico o histeria colectiva en concentraciones masivas.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (27,'PESTES','PLAGUE','Proliferación de bichos.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (4,'PLUIE','RAINS','Aguacero, chaparrón, chubasco, diluvio.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (3,'INONDATION TORRENTIELLE','FLASH FLOOD','Avenida torrencial, avalancha');
insert into eventos (serial,nombre,nombre_en,descripcion) values (32,'POLLUTION','CONTAMINATION','Contaminación ambiental, hídrica o en suelos.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (13,'SÉCHERESSE','DROUGHT','Temporada seca.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (10,'SÉDIMENTATION','SEDIMENTATION','Depositación de material sólido por erosión, colmatación.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (24,'EFFONDREMENT STRUCTURE','STRUCTURAL COLLAPSE','Daño o colapso de cualquier tipo de estructura.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (6,'TEMPÊTE','STORM','Lluvia con vientos fuertes y descargas eléctricas.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (5,'TEMPETE DE VENTS','WINDSTORM','Vientos fuertes. Temporal, ventisca, borrasca.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (36,'TORNADO','TORNADO','Vientos fuertes en remolino y forma de embudo que tocan la tierra.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (8,'TREMBLEMENT DE TERRE','EARTHQUAKE','Movimiento de la corteza terrestre. Temblor, terremoto.');
insert into eventos (serial,nombre,nombre_en,descripcion) values (17,'TSUNAMI','TSUNAMI','Maremoto. Grandes olas causadas por movimientos en el fondo del mar.');

Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Pluie','Rain');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Inondation','Flood');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Glissement terrain','Landslide');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Tremblement de terre','Earthquake');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Eruption','Eruption');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Sécheresse','Drought');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Tempête','Storm');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Tempête de Vents','Windstorm');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Brume','Fog');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Pest','Plague');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Contamination','Contamination');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Inversion thermal','Thermal inversion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('El Niño','El Niño');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('La Niña','La Niña');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Fault','Fault');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Comportement','Behaviour');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Error','Error');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Negligence','Negligence');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Deforestation','Deforestation');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Court-circuit','Shortcircuit');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Deterioration','Deterioration');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Cond.Atmosph.','Cond.Atmosph.');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Depression Trop.','Trop.Depresion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Erosion','Erosion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Fuite toxique','Leak');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Explosion','Explosion');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Location','Location');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('INCONNU','Unknown');
Insert into CAUSAS (CAUSA,CAUSA_EN) values ('Other cause','Other cause');



