INSERT INTO eventos VALUES (1, 'НАВОДНЕНИЕ', 'FLOOD', 'Затопление территории водой, являющееся стихийным бедствием', NULL, NULL, NULL);
INSERT INTO eventos VALUES (2, 'ОПОЛЗЕНЬ', 'LANDSLIDE', 'Смещение масс земной поверхности', NULL, NULL, NULL);
INSERT INTO eventos VALUES (3, 'СТИХ.НАВОДНЕНИЕ', 'FLASH FLOOD', 'Внезапное наводнение в результате ливневых дождей', NULL, NULL, NULL);
INSERT INTO eventos VALUES (4, 'ДОЖДИ', 'RAINS', 'Осадки в виде дождя. Ливень, шквал, сильный дождь и т.д.', NULL, NULL, NULL);
INSERT INTO eventos VALUES (5, 'СИЛЬНЫЙ ВЕТЕР', 'WINDSTORM', 'Сильные ветры. Вихрь, шквал, метель, и порывы.', NULL, NULL, NULL);
INSERT INTO eventos VALUES (6, 'ШТОРМ', 'STORM', 'Дождь с сильными ветрами и / или грозовыми разрядами', NULL, NULL, NULL);
INSERT INTO eventos VALUES (7, 'ВЫСОКАЯ ВОЛНА', 'SURGE', 'Сильные морские волны разрушающие набережную (исключение цунами)', NULL, NULL, NULL);
INSERT INTO eventos VALUES (8, 'ЗЕМЛЕТРЯСЕНИЕ', 'EARTHQUAKE', 'Любое движение земной коры. Тремор, вибрация', NULL, NULL, NULL);
INSERT INTO eventos VALUES (9, 'ЦИКЛОН', 'CYCLONE', 'Тропический шторм. Циклон, тайфун', NULL, NULL, NULL);
INSERT INTO eventos VALUES (10, 'ОТЛОЖ.ОСАДКА', 'SEDIMENTATION', 'Депозит твердого материала на склонах и руслах рек', NULL, NULL, NULL);
INSERT INTO eventos VALUES (11, 'МОРОЗ', 'FROST', 'Низкие значения температуры', NULL, NULL, NULL);
INSERT INTO eventos VALUES (12, 'ГРОЗА С ГРАДОМ', 'HAILSTORM', 'Осадки в виде града', NULL, NULL, NULL);
INSERT INTO eventos VALUES (13, 'ЗАСУХА', 'DROUGHT', 'Сухой сезон без дождя или с дефицитом дождя', NULL, NULL, NULL);
INSERT INTO eventos VALUES (14, 'ИЗМ.БЕРЕГ.ЛИНИИ', 'COASTLINE', 'Изменение береговой линии', NULL, NULL, NULL);
INSERT INTO eventos VALUES (15, 'СЕЛЬ', 'MUDSLIDE', 'Грязевой поток, перемещающий большое количество твердого материала', NULL, NULL, NULL);
INSERT INTO eventos VALUES (16, 'ЛАВИНА', 'AVALANCHE', 'Стремительное скольжение разрыхлённого льда или снежных масс', NULL, NULL, NULL);
INSERT INTO eventos VALUES (18, 'РАЗЖ.ГРУНТОВ', 'LIQUEFACTION', 'Потеря несущей способности грунта. Характерно для насыщенных влагой сыпучих грунтов, как илистые пески.', NULL, NULL, NULL);
INSERT INTO eventos VALUES (20, 'ПОЖАР', 'FIRE', 'Городские, сельские или промышленные пожары (исключение лесной пожар)', NULL, NULL, NULL);
INSERT INTO eventos VALUES (21, 'ЛЕСНОЙ ПОЖАР', 'FOREST FIRE', 'Лесной пожар, пожар в натуральных условиях', NULL, NULL, NULL);
INSERT INTO eventos VALUES (23, 'УТЕЧКА', 'LEAK', 'Утечка опасных жидких, твердых или газообразных веществ', NULL, NULL, NULL);
INSERT INTO eventos VALUES (24, 'СТРУКТУР.КОЛЛАПС', 'STRUCTURE', 'Повреждение или разрушение любого типа конструкции', NULL, NULL, NULL);
INSERT INTO eventos VALUES (25, 'ПАНИКА', 'PANIC', 'Паника или массовая истерия среди массы людей, сосредоточенных в одном месте', NULL, NULL, NULL);
INSERT INTO eventos VALUES (26, 'ЭПИДЕМИЯ', 'EPIDEMIC', 'Опасная болезнь атакующая большое кол-во людей в определенной зоне', NULL, NULL, NULL);
INSERT INTO eventos VALUES (27, 'ИНФЕКЦ.ЗАБОЛЕВАНИЕ', 'PLAGUE', 'Стремительное распространение болезни', NULL, NULL, NULL);
INSERT INTO eventos VALUES (28, 'АВАРИЯ', 'ACCIDENT', 'Автомобильные, железнодорожные, авиационные или навигационные происшествия', NULL, NULL, NULL);
INSERT INTO eventos VALUES (29, 'ДРУГОЕ', 'OTHER', 'Другой тип бедствия, отсутствующий в перечне', NULL, NULL, NULL);
INSERT INTO eventos VALUES (30, 'БИО.ЗАРАЖЕНИЕ', 'BIOLOGICAL', 'Гибель животных, с/х растений, в резулт.поражения вирусом, грибком, бактериями, паразитами', NULL, NULL, NULL);
INSERT INTO eventos VALUES (31, 'ИЗВЕРЖЕНИЕ', 'ERUPTION', 'Извержение вулкана. Включает выбросы газов, пепла, камней и т.д.', NULL, NULL, NULL);
INSERT INTO eventos VALUES (32, 'ЗАГРЯЗНЕНИЕ', 'CONTAMINATION', 'Загрязнение окружающей среды', NULL, NULL, NULL);
INSERT INTO eventos VALUES (33, 'ГРОЗА', 'THUNDERSTORM', 'Атмосферные статистические разряды, молния', NULL, NULL, NULL);
INSERT INTO eventos VALUES (34, 'МЕТЕЛЬ', 'SNOWSTORM', 'Сильный ветер со снегом, накопление снежных осадков', NULL, NULL, NULL);
INSERT INTO eventos VALUES (35, 'СИЛЬНАЯ ЖАРА', 'HEAT WAVE', 'Повышенные значения температуры воздуха в теч.продолжит.периода', NULL, NULL, NULL);
INSERT INTO eventos VALUES (37, 'ТУМАН', 'FOG', 'Концентрация водяного пара над земной поверхностью', NULL, NULL, NULL);
INSERT INTO eventos VALUES (38, 'ИНТОКСИКАЦИЯ', 'INTOXICATION', 'Отравление человека, болезненное состояние, обусловл.действием на организм экзогенных токсинов', NULL, NULL, NULL);
INSERT INTO eventos VALUES (39, 'РЕЗКОЕ ПОХОЛОДАНИЕ', 'COLD WAVE', 'Резкое понижение температуры воздуха', NULL, NULL, NULL);
INSERT INTO eventos VALUES (17, 'ЦУНАМИ', 'TSUNAMI', 'Высокие волны порождаемые подвод.землетрясениями', NULL, NULL, NULL);
INSERT INTO eventos VALUES (22, 'ВЗРЫВ', 'EXPLOSION', 'Взрывы любого типа (исключение террористический акт)', NULL, NULL, NULL);
INSERT INTO eventos VALUES (36, 'ТОРНАДО', 'TORNADO', 'Атмосферный вихрь, возникающий в грозовом облаке и распространяющийся вниз в виде облачного рукава', NULL, NULL, NULL);


INSERT INTO causas VALUES ('Дождь', 'Rain');
INSERT INTO causas VALUES ('Наводнение', 'Flood');
INSERT INTO causas VALUES ('Землетрясение', 'Earthquake');
INSERT INTO causas VALUES ('Оползень', 'Landslide');
INSERT INTO causas VALUES ('Неисправность', 'Fault');
INSERT INTO causas VALUES ('Вырубка леса', 'Deforestation');
INSERT INTO causas VALUES ('Чел.фактор', 'H. Behaviour');
INSERT INTO causas VALUES ('Ошибка', 'Error');
INSERT INTO causas VALUES ('Строит.ошибка', 'Design');
INSERT INTO causas VALUES ('Эль Ниньо', 'El Nino');
INSERT INTO causas VALUES ('Др.причина', 'Other cause');
INSERT INTO causas VALUES ('Атм.явление', 'Cond.Atmosph.');
INSERT INTO causas VALUES ('Загрязнение', 'Contamination');
INSERT INTO causas VALUES ('Корот.замыкание', 'Shortcircuit');
INSERT INTO causas VALUES ('Тропич.циклон', 'Trop.Depresion');
INSERT INTO causas VALUES ('Паводок', 'Overflow');
INSERT INTO causas VALUES ('Износ', 'Deterioration');
INSERT INTO causas VALUES ('Неизвестно', 'Unknown');
INSERT INTO causas VALUES ('Ла Нинья', 'La Nina');
INSERT INTO causas VALUES ('Извержение', 'Eruption');
INSERT INTO causas VALUES ('Утечка', 'Leak');
INSERT INTO causas VALUES ('Темп.инверсия', 'Thermal inversion');
INSERT INTO causas VALUES ('Местонахождение', 'Location');
INSERT INTO causas VALUES ('Туман', 'Fog');
INSERT INTO causas VALUES ('Халатность', 'Negligence');
INSERT INTO causas VALUES ('Инфекц.заболевание', 'Plague');
INSERT INTO causas VALUES ('Засуха', 'Drought');
INSERT INTO causas VALUES ('Чрезм.эксплуат.', 'Overexploit');
INSERT INTO causas VALUES ('Гроза', 'Storm');
INSERT INTO causas VALUES ('Сильный ветер', 'Windstorm');
INSERT INTO causas VALUES ('Эрозия', 'Erosion');
INSERT INTO causas VALUES ('Взрыв', 'Explosion');



