--delete from diccionario;
--delete from extension;
--drop table extension;

--CREATE TABLE extension (
--	clave_ext int NOT NULL 
--); 
--ALTER TABLE extension ADD 
--	CONSTRAINT FK_extension_fichas FOREIGN KEY 
--	(
--		clave_ext
--	) REFERENCES fichas (
--		clave
--	); 
--


insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (1,'DEATHS_FEMALE','Deaths female','Deaths female','Deaths female',0,0,7,0,0,null,1);
alter table extension add DEATHS_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (2,'DEATHS_MALE','Deaths male','Deaths male','Deaths male',0,0,7,0,0,null,1);
alter table extension add DEATHS_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (3,'DEATHS_CHILDREN','Deaths children','Deaths children','Deaths children',0,0,7,0,0,null,1);
alter table extension add DEATHS_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (4,'DEATHS_ADULTS','Deaths adults','Deaths adults','Deaths adults',0,0,7,0,0,null,1);
alter table extension add DEATHS_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (5,'DEATHS_ELDER','Deaths elder','Deaths elder','Deaths elder',0,0,7,0,0,null,1);
alter table extension add DEATHS_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (6,'DEATHS_DISABLED','Deaths disabled','Deaths disabled','Deaths disabled',0,0,7,0,0,null,1);
alter table extension add DEATHS_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (7,'DEATHS_POOR','Deaths poor','Deaths poor','Deaths poor',0,0,7,0,0,null,1);
alter table extension add DEATHS_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (8,'MISSING_FEMALE','Missing female','Missing female','Missing female',0,0,7,0,0,null,1);
alter table extension add MISSING_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (9,'MISSING_MALE','Missing male','Missing male','Missing male',0,0,7,0,0,null,1);
alter table extension add MISSING_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (10,'MISSING_CHILDREN','Missing children','Missing children','Missing children',0,0,7,0,0,null,1);
alter table extension add MISSING_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (11,'MISSING_ADULTS','Missing adults','Missing adults','Missing adults',0,0,7,0,0,null,1);
alter table extension add MISSING_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (12,'MISSING_ELDER','Missing elder','Missing elder','Missing elder',0,0,7,0,0,null,1);
alter table extension add MISSING_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (13,'MISSING_DISABLED','Missing disabled','Missing disabled','Missing disabled',0,0,7,0,0,null,1);
alter table extension add MISSING_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (14,'MISSING_POOR','Missing poor','Missing poor','Missing poor',0,0,7,0,0,null,1);
alter table extension add MISSING_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (15,'INJURED_FEMALE','Injured female','Injured female','Injured female',0,0,7,0,0,null,1);
alter table extension add INJURED_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (16,'INJURED_MALE','Injured male','Injured male','Injured male',0,0,7,0,0,null,1);
alter table extension add INJURED_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (17,'INJURED_CHILDREN','Injured children','Injured children','Injured children',0,0,7,0,0,null,1);
alter table extension add INJURED_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (18,'INJURED_ADULTS','Injured adults','Injured adults','Injured adults',0,0,7,0,0,null,1);
alter table extension add INJURED_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (19,'INJURED_ELDER','Injured elder','Injured elder','Injured elder',0,0,7,0,0,null,1);
alter table extension add INJURED_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (20,'INJURED_DISABLED','Injured disabled','Injured disabled','Injured disabled',0,0,7,0,0,null,1);
alter table extension add INJURED_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (21,'INJURED_POOR','Injured poor','Injured poor','Injured poor',0,0,7,0,0,null,1);
alter table extension add INJURED_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (22,'LIVING_DMGD_DWELLINGS','Living damaged dwellings','Living damaged dwellings','Living damaged dwellings',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (23,'LIVING_DMGD_DWELLINGS_FEMALE','Living damaged dwellings female','Living damaged dwellings female','Living damaged dwellings female',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (24,'LIVING_DMGD_DWELLINGS_MALE','Living damaged dwellings male','Living damaged dwellings male','Living damaged dwellings male',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (25,'LIVING_DMGD_DWELLINGS_CHILDREN','Living damaged dwellings children','Living damaged dwellings children','Living damaged dwellings children',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (26,'LIVING_DMGD_DWELLINGS_ADULTS','Living damaged dwellings adults','Living damaged dwellings adults','Living damaged dwellings adults',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (27,'LIVING_DMGD_DWELLINGS_ELDER','Living damaged dwellings elder','Living damaged dwellings elder','Living damaged dwellings elder',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (28,'LIVING_DMGD_DWELLINGS_DISABLED','Living damaged dwellings disabled','Living damaged dwellings disabled','Living damaged dwellings disabled',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (29,'LIVING_DMGD_DWELLINGS_POOR','Living damaged dwellings poor','Living damaged dwellings poor','Living damaged dwellings poor',0,0,7,0,0,null,1);
alter table extension add LIVING_DMGD_DWELLINGS_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (30,'LIVING_DSTR_DWELLINGS','Living destroyed dwellings','Living destroyed dwellings','Living destroyed dwellings',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (31,'LIVING_DSTR_DWELLINGS_FEMALE','Living destroyed dwellings female','Living destroyed dwellings female','Living destroyed dwellings female',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (32,'LIVING_DSTR_DWELLINGS_MALE','Living destroyed dwellings male','Living destroyed dwellings male','Living destroyed dwellings male',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (33,'LIVING_DSTR_DWELLINGS_CHILDREN','Living destroyed dwellings children','Living destroyed dwellings children','Living destroyed dwellings children',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (34,'LIVING_DSTR_DWELLINGS_ADULTS','Living destroyed dwellings adults','Living destroyed dwellings adults','Living destroyed dwellings adults',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (35,'LIVING_DSTR_DWELLINGS_ELDER','Living destroyed dwellings elder','Living destroyed dwellings elder','Living destroyed dwellings elder',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (36,'LIVING_DSTR_DWELLINGS_DISABLED','Living destroyed dwellings disabled','Living destroyed dwellings disabled','Living destroyed dwellings disabled',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (37,'LIVING_DSTR_DWELLINGS_POOR','Living destroyed dwellings poor','Living destroyed dwellings poor','Living destroyed dwellings poor',0,0,7,0,0,null,1);
alter table extension add LIVING_DSTR_DWELLINGS_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (38,'LIVELIHOOD_AFCTD','Livelihood affected','Livelihood affected','Livelihood affected',0,0,7,0,0,null,1);
alter table extension add LIVELIHOOD_AFCTD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (39,'LIVELIHOODS_FEMALE','Livelihoods female','Livelihoods female','Livelihoods female',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_FEMALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (40,'LIVELIHOODS_MALE','Livelihoods male','Livelihoods male','Livelihoods male',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_MALE int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (41,'LIVELIHOODS_CHILDREN','Livelihoods children','Livelihoods children','Livelihoods children',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_CHILDREN int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (42,'LIVELIHOODS_ADULTS','Livelihoods adults','Livelihoods adults','Livelihoods adults',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_ADULTS int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (43,'LIVELIHOODS_ELDER','Livelihoods elder','Livelihoods elder','Livelihoods elder',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_ELDER int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (44,'LIVELIHOODS_DISABLED','Livelihoods disabled','Livelihoods disabled','Livelihoods disabled',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_DISABLED int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (45,'LIVELIHOODS_POOR','Livelihoods poor','Livelihoods poor','Livelihoods poor',0,0,7,0,0,null,1);
alter table extension add LIVELIHOODS_POOR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (46,'daminificados','daminificados','daminificados','daminificados',0,0,7,0,0,null,1);
alter table extension add daminificados int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (47,'HA_DMGD','Ha damaged','Ha damaged','Ha damaged',0,0,15,0,0,null,2);
alter table extension add HA_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (48,'HA_DSTR','Ha destroyed','Ha destroyed','Ha destroyed',0,0,15,0,0,null,2);
alter table extension add HA_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (49,'LOSS_CROPS','Loss from crops','Loss from crops','Loss from crops',0,0,15,0,0,null,2);
alter table extension add LOSS_CROPS float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (50,'LOSS_DMGD_CROPS','Loss from damaged crops','Loss from damaged crops','Loss from damaged crops',0,0,15,0,0,null,2);
alter table extension add LOSS_DMGD_CROPS float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (51,'LOSS_DSTR_CROPS','Loss from destroyed crops','Loss from destroyed crops','Loss from destroyed crops',0,0,15,0,0,null,2);
alter table extension add LOSS_DSTR_CROPS float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (52,'LIVESTOCK_TOTAL','Livestock total','Livestock total','Livestock total',0,0,7,0,0,null,1);
alter table extension add LIVESTOCK_TOTAL int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (53,'LIVESTOCK_DMGD','Livestock damaged','Livestock damaged','Livestock damaged',0,0,7,0,0,null,1);
alter table extension add LIVESTOCK_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (54,'LOSS_LIVESTOCK_TOTAL','Loss from livestock total','Loss from livestock total','Loss from livestock total',0,0,15,0,0,null,2);
alter table extension add LOSS_LIVESTOCK_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (55,'LOSS_LIVESTOCK_DMGD','Loss from livestock damaged','Loss from livestock damaged','Loss from livestock damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_LIVESTOCK_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (56,'LOSS_LIVESTOCK_DSTR','Loss from livestock destroyed','Loss from livestock destroyed','Loss from livestock destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_LIVESTOCK_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (57,'HA_FOREST_TOTAL','Ha forest total','Ha forest total','Ha forest total',0,0,15,0,0,null,2);
alter table extension add HA_FOREST_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (58,'HA_FOREST_DMGD','Ha forest damaged','Ha forest damaged','Ha forest damaged',0,0,15,0,0,null,2);
alter table extension add HA_FOREST_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (59,'HA_FOREST_DSTR','Ha forest destroyed','Ha forest destroyed','Ha forest destroyed',0,0,15,0,0,null,2);
alter table extension add HA_FOREST_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (60,'LOSS_FOREST_TOTAL','Loss from forest total','Loss from forest total','Loss from forest total',0,0,15,0,0,null,2);
alter table extension add LOSS_FOREST_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (61,'LOSS_FOREST_DMGD','Loss from forest damaged','Loss from forest damaged','Loss from forest damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_FOREST_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (62,'LOSS_FOREST_DSTR','Loss from forest destroyed','Loss from forest destroyed','Loss from forest destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_FOREST_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (63,'HA_AQUACULTURE_TOTAL','Ha aquaculture total','Ha aquaculture total','Ha aquaculture total',0,0,15,0,0,null,2);
alter table extension add HA_AQUACULTURE_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (64,'HA_AQUACULTURE_DMGD','Ha aquaculture damaged','Ha aquaculture damaged','Ha aquaculture damaged',0,0,15,0,0,null,2);
alter table extension add HA_AQUACULTURE_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (65,'HA_AQUACULTURE_DSTR','Ha aquaculture destroyed','Ha aquaculture destroyed','Ha aquaculture destroyed',0,0,15,0,0,null,2);
alter table extension add HA_AQUACULTURE_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (66,'LOSS_AQUACULTURE_TOTAL','Loss from aquaculture total','Loss from aquaculture total','Loss from aquaculture total',0,0,15,0,0,null,2);
alter table extension add LOSS_AQUACULTURE_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (67,'LOSS_AQUACULTURE_DMGD','Loss from aquaculture damaged','Loss from aquaculture damaged','Loss from aquaculture damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_AQUACULTURE_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (68,'LOSS_AQUACULTURE_DSTR','Loss from aquaculture destroyed','Loss from aquaculture destroyed','Loss from aquaculture destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_AQUACULTURE_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (69,'VESSELS_TOTAL','Vessels total','Vessels total','Vessels total',0,0,7,0,0,null,1);
alter table extension add VESSELS_TOTAL int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (70,'VESSELS_DMGD','Vessels damaged','Vessels damaged','Vessels damaged',0,0,7,0,0,null,1);
alter table extension add VESSELS_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (71,'VESSELS_DSTR','Vessels destroyed','Vessels destroyed','Vessels destroyed',0,0,7,0,0,null,1);
alter table extension add VESSELS_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (72,'LOSS_VESSELS_TOTAL','Loss from vessels total','Loss from vessels total','Loss from vessels total',0,0,15,0,0,null,2);
alter table extension add LOSS_VESSELS_TOTAL float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (73,'LOSS_VESSELS_DMGD','Loss from vessels damaged','Loss from vessels damaged','Loss from vessels damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_VESSELS_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (74,'LOSS_VESSELS_DSTR','Loss from vessels destroyed','Loss from vessels destroyed','Loss from vessels destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_VESSELS_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (75,'STOCK_FACILITIES_AFCTD','Stock facilities affected','Stock facilities affected','Stock facilities affected',0,0,7,0,0,null,1);
alter table extension add STOCK_FACILITIES_AFCTD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (76,'STOCK_FACILITIES_DMGD','Stock facilities damaged','Stock facilities damaged','Stock facilities damaged',0,0,7,0,0,null,1);
alter table extension add STOCK_FACILITIES_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (77,'STOCK_FACILITIES_DSTR','Stock facilities destroyed','Stock facilities destroyed','Stock facilities destroyed',0,0,7,0,0,null,1);
alter table extension add STOCK_FACILITIES_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (78,'STOCK_LOSS_AFCTD','Stock loss affected','Stock loss affected','Stock loss affected',0,0,15,0,0,null,2);
alter table extension add STOCK_LOSS_AFCTD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (79,'STOCK_LOSS_DMGD','Stock loss damaged','Stock loss damaged','Stock loss damaged',0,0,15,0,0,null,2);
alter table extension add STOCK_LOSS_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (80,'STOCK_LOSS_DSTR','Stock loss destroyed','Stock loss destroyed','Stock loss destroyed',0,0,15,0,0,null,2);
alter table extension add STOCK_LOSS_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (81,'AGRI_ASSETS_AFCTD','Agricultural assets affected','Agricultural assets affected','Agricultural assets affected',0,0,7,0,0,null,1);
alter table extension add AGRI_ASSETS_AFCTD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (82,'AGRI_ASSETS_DMGD','Agricultural assets damaged','Agricultural assets damaged','Agricultural assets damaged',0,0,7,0,0,null,1);
alter table extension add AGRI_ASSETS_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (83,'AGRI_ASSETS_DSTR','Agricultural assets destroyed','Agricultural assets destroyed','Agricultural assets destroyed',0,0,7,0,0,null,1);
alter table extension add AGRI_ASSETS_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (84,'AGRI_ASSETS_LOSS_AFCTD','Agricultural assets loss affected','Agricultural assets loss affected','Agricultural assets loss affected',0,0,15,0,0,null,2);
alter table extension add AGRI_ASSETS_LOSS_AFCTD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (85,'AGRI_ASSETS_LOSS_DMGD','Agricultural assets loss damaged','Agricultural assets loss damaged','Agricultural assets loss damaged',0,0,15,0,0,null,2);
alter table extension add AGRI_ASSETS_LOSS_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (86,'AGRI_ASSETS_LOSS_DSTR','Agricultural assets loss destroyed','Agricultural assets loss destroyed','Agricultural assets loss destroyed',0,0,15,0,0,null,2);
alter table extension add AGRI_ASSETS_LOSS_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (87,'PRODUCTIVE_ASSETS_AFCTD','Productive assets affected','Productive assets affected','Productive assets affected',0,0,7,0,0,null,1);
alter table extension add PRODUCTIVE_ASSETS_AFCTD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (88,'PRODUCTIVE_ASSETS_DMGD','Productive assets damaged','Productive assets damaged','Productive assets damaged',0,0,7,0,0,null,1);
alter table extension add PRODUCTIVE_ASSETS_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (89,'PRODUCTIVE_ASSETS_DSTR','Productive assets destroyed','Productive assets destroyed','Productive assets destroyed',0,0,7,0,0,null,1);
alter table extension add PRODUCTIVE_ASSETS_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (90,'PRODUCTIVE_ASSETS_LOSS_AFCTD','Productive assets loss affected','Productive assets loss affected','Productive assets loss affected',0,0,15,0,0,null,2);
alter table extension add PRODUCTIVE_ASSETS_LOSS_AFCTD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (91,'PRODUCTIVE_ASSETS_LOSS_DMGD','Productive assets loss damaged','Productive assets loss damaged','Productive assets loss damaged',0,0,15,0,0,null,2);
alter table extension add PRODUCTIVE_ASSETS_LOSS_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (92,'PRODUCTIVE_ASSETS_LOSS_DSTR','Productive assets loss destroyed','Productive assets loss destroyed','Productive assets loss destroyed',0,0,15,0,0,null,2);
alter table extension add PRODUCTIVE_ASSETS_LOSS_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (93,'HOUSES_TOTAL','Houses total','Houses total','Houses total',0,0,7,0,0,null,1);
alter table extension add HOUSES_TOTAL int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (94,'LOSS_DWELLINGS','Loss from dwellings','Loss from dwellings','Loss from dwellings',0,0,15,0,0,null,2);
alter table extension add LOSS_DWELLINGS float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (95,'LOSS_DWELLINGS_DMGD','Loss from dwellings damaged','Loss from dwellings damaged','Loss from dwellings damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_DWELLINGS_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (96,'LOSS__DWELLINGSDSTR','Loss from  dwellingsdestroyed','Loss from  dwellingsdestroyed','Loss from  dwellingsdestroyed',0,0,15,0,0,null,2);
alter table extension add LOSS__DWELLINGSDSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (97,'HEALTH_FACILITIES_DMGD','Health facilities damaged','Health facilities damaged','Health facilities damaged',0,0,7,0,0,null,1);
alter table extension add HEALTH_FACILITIES_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (98,'HEALTH_FACILITIES_DSTR','Health facilities destroyed','Health facilities destroyed','Health facilities destroyed',0,0,7,0,0,null,1);
alter table extension add HEALTH_FACILITIES_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (99,'LOSS_HEALTH_FACILITIES','Loss from health facilities','Loss from health facilities','Loss from health facilities',0,0,12,0,0,null,2);
alter table extension add LOSS_HEALTH_FACILITIES float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (100,'LOSS_HEALTH_FACILITIES_DMGD','Loss from health facilities damaged','Loss from health facilities damaged','Loss from health facilities damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_HEALTH_FACILITIES_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (101,'LOSS_HEALTH_FACILITIES_DSTR','Loss from health facilities destroyed','Loss from health facilities destroyed','Loss from health facilities destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_HEALTH_FACILITIES_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (102,'EDUCATION_DMGD','Education damaged','Education damaged','Education damaged',0,0,7,0,0,null,1);
alter table extension add EDUCATION_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (103,'EDUCATION_DSTR','Education destroyed','Education destroyed','Education destroyed',0,0,7,0,0,null,1);
alter table extension add EDUCATION_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (104,'LOSS_EDUCATION','Loss from education','Loss from education','Loss from education',0,0,15,0,0,null,2);
alter table extension add LOSS_EDUCATION float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (105,'LOSS_EDUCATION_DMGD','Loss from education damaged','Loss from education damaged','Loss from education damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_EDUCATION_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (106,'LOSS_EDUCATION_DSTR','Loss from education destroyed','Loss from education destroyed','Loss from education destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_EDUCATION_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (107,'NUMBER_INFRASTRUCTURES','Number infrastructures','Number infrastructures','Number infrastructures',0,0,7,0,0,null,1);
alter table extension add NUMBER_INFRASTRUCTURES int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (108,'NUMBER_DMGD_INFRASTRUCTURES','Number damaged infrastructures','Number damaged infrastructures','Number damaged infrastructures',0,0,7,0,0,null,1);
alter table extension add NUMBER_DMGD_INFRASTRUCTURES int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (109,'NUMBER_DSTR_INFRASTRUCTURES','Number destroyed infrastructures','Number destroyed infrastructures','Number destroyed infrastructures',0,0,7,0,0,null,1);
alter table extension add NUMBER_DSTR_INFRASTRUCTURES int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (110,'LOSS_INFRASTRUCTURES','Loss from infrastructures','Loss from infrastructures','Loss from infrastructures',0,0,15,0,0,null,2);
alter table extension add LOSS_INFRASTRUCTURES float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (111,'LOSS_DMGD_INFRASTRUCTURES','Loss from damaged infrastructures','Loss from damaged infrastructures','Loss from damaged infrastructures',0,0,15,0,0,null,2);
alter table extension add LOSS_DMGD_INFRASTRUCTURES float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (112,'LOSS_DSTR_INFRASTRUCTURES','Loss from destroyed infrastructures','Loss from destroyed infrastructures','Loss from destroyed infrastructures',0,0,15,0,0,null,2);
alter table extension add LOSS_DSTR_INFRASTRUCTURES float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (113,'LOSS_CULTURAL_FIXED','Loss from cultural fixed','Loss from cultural fixed','Loss from cultural fixed',0,0,15,0,0,null,2);
alter table extension add LOSS_CULTURAL_FIXED float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (114,'LOSS_CULTURAL_MOBILE_DMGD','Loss from cultural mobile damaged','Loss from cultural mobile damaged','Loss from cultural mobile damaged',0,0,15,0,0,null,2);
alter table extension add LOSS_CULTURAL_MOBILE_DMGD float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (115,'LOSS_CULTURAL_MOBILE_DSTR','Loss from cultural mobile destroyed','Loss from cultural mobile destroyed','Loss from cultural mobile destroyed',0,0,15,0,0,null,2);
alter table extension add LOSS_CULTURAL_MOBILE_DSTR float;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (116,'CULTURAL_FIXED_DMGD','Cultural fixed damaged','Cultural fixed damaged','Cultural fixed damaged',0,0,7,0,0,null,1);
alter table extension add CULTURAL_FIXED_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (117,'CULTURAL_FIXED_DSTR','Cultural fixed destroyed','Cultural fixed destroyed','Cultural fixed destroyed',0,0,7,0,0,null,1);
alter table extension add CULTURAL_FIXED_DSTR int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (118,'CULTURAL_MOBILE_DMGD','Cultural mobile damaged','Cultural mobile damaged','Cultural mobile damaged',0,0,7,0,0,null,1);
alter table extension add CULTURAL_MOBILE_DMGD int;
insert into diccionario (orden,nombre_campo,descripcion_campo,label_campo,label_campo_en,pos_x,pos_y,lon_x,lon_y,color,tabnumber,fieldtype) values (119,'CULTURAL_MOBILE_DSTR','Cultural mobile destroyed','Cultural mobile destroyed','Cultural mobile destroyed',0,0,7,0,0,null,1);
alter table extension add CULTURAL_MOBILE_DSTR int;
 