update eventos set nombre_en='FLOOD' where nombre= 'INUNDACION';
update eventos set nombre_en='LANDSLIDE' where nombre= 'DESLIZAMIENTO';
update eventos set nombre_en='FLASH FLOOD' where nombre= 'AVENIDA';
update eventos set nombre_en='RAINS' where nombre= 'LLUVIAS';
update eventos set nombre_en='STRONG WIND' where nombre= 'VENDAVAL';
update eventos set nombre_en='STORM' where nombre= 'TEMPESTAD';
update eventos set nombre_en='HIGH TIDE' where nombre= 'MAREJADA';
update eventos set nombre_en='EARTHQUAKE' where nombre= 'SISMO';
update eventos set nombre_en='HURRICANE' where nombre= 'HURACAN';
update eventos set nombre_en='SEDIMENTATION' where nombre= 'SEDIMENTACION';
update eventos set nombre_en='FROST' where nombre= 'HELADA';
update eventos set nombre_en='HAILSTORM' where nombre= 'GRANIZADA';
update eventos set nombre_en='DROUGHT' where nombre= 'SEQUIA';
update eventos set nombre_en='COASTLINE' where nombre= 'LITORAL';
update eventos set nombre_en='ALLUVION' where nombre= 'ALUVION';
update eventos set nombre_en='AVALANCHE' where nombre= 'ALUD';
update eventos set nombre_en='TSUNAMI' where nombre= 'TSUNAMI';
update eventos set nombre_en='LIQUEFACTION' where nombre= 'LICUACION';
update eventos set nombre_en='FAILURE' where nombre= 'FALLA';
update eventos set nombre_en='FIRE' where nombre= 'INCENDIO';
update eventos set nombre_en='FOREST FIRE' where nombre= 'FORESTAL';
update eventos set nombre_en='EXPLOSION' where nombre= 'EXPLOSION';
update eventos set nombre_en='LEAK' where nombre= 'ESCAPE';
update eventos set nombre_en='STRUCTURE' where nombre= 'ESTRUCTURA';
update eventos set nombre_en='PANIC' where nombre= 'PANICO';
update eventos set nombre_en='EPIDEMIC' where nombre= 'EPIDEMIA';
update eventos set nombre_en='PLAGUE' where nombre= 'PLAGA';
update eventos set nombre_en='ACCIDENT' where nombre= 'ACCIDENTE';
update eventos set nombre_en='OTHER' where nombre= 'OTROS';
update eventos set nombre_en='BIOLOGICAL' where nombre= 'BIOLOGICO';
update eventos set nombre_en='ERUPTION' where nombre= 'ERUPCION';
update eventos set nombre_en='CONTAMINATION' where nombre= 'CONTAMINACION';
update eventos set nombre_en='ELECTRIC STORM' where  nombre='TORMENTA E.';
update eventos set nombre_en='SNOWSTORM' where nombre= 'NEVADA';
update eventos set nombre_en='HEAT WAVE' where nombre='OLA DE CALOR' ;
update eventos set nombre_en='COLD WAVE'  where nombre= 'OLA DE FRIO';
update eventos set nombre_en='TORNADO' where nombre= 'TORNADO';
update eventos set nombre_en='FOG' where nombre= 'NEBLINA';
update eventos set nombre_en='INTOXICATION' where nombre= 'INTOXICACION';
update eventos set nombre_en='EPIZOOTIC' where nombre= 'EPIZOOTIA';
update eventos set nombre_en='FOG' where nombre= 'NIEBLA';
update eventos set nombre_en='ACCIDENT' where nombre= 'A. TRANSITO';
update eventos set nombre_en='ACCIDENT' where nombre= 'ACCIDENTE TRANS';
update eventos set nombre_en='FAMINE' where nombre= 'HAMBRUNA';
update eventos set nombre_en='STORM' where nombre= 'TORMENTA TROPIC';
update eventos set nombre_en='FAMINE' where nombre= 'RACIONAMIENTO';
update eventos set nombre_en='COLD WAVE'  where nombre= 'ONDA FRIA';

update eventos set nombre_en='FLOOD' where nombre= 'INUNDACION';
update eventos set nombre_en='LANDSLIDE' where nombre= 'DESLIZAMIENTO';
update eventos set nombre_en='FLASH FLOOD' where nombre= 'AVENIDA';
update eventos set nombre_en='RAINS' where nombre= 'LLUVIAS';
update eventos set nombre_en='STRONG WIND' where nombre= 'VENDAVAL';
update eventos set nombre_en='STORM' where nombre= 'TEMPESTAD';
update eventos set nombre_en='HIGH TIDE' where nombre= 'MAREJADA';
update eventos set nombre_en='EARTHQUAKE' where nombre= 'SISMO';
update eventos set nombre_en='HURRICANE' where nombre= 'HURACAN';
update eventos set nombre_en='SEDIMENTATION' where nombre= 'SEDIMENTACION';
update eventos set nombre_en='FROST' where nombre= 'HELADA';
update eventos set nombre_en='HAILSTORM' where nombre= 'GRANIZADA';
update eventos set nombre_en='DROUGHT' where nombre= 'SEQUIA';
update eventos set nombre_en='COASTLINE' where nombre= 'LITORAL';
update eventos set nombre_en='ALLUVION' where nombre= 'ALUVION';
update eventos set nombre_en='AVALANCHE' where nombre= 'ALUD';
update eventos set nombre_en='TSUNAMI' where nombre= 'TSUNAMI';
update eventos set nombre_en='LIQUEFACTION' where nombre= 'LICUACION';
update eventos set nombre_en='FAILURE' where nombre= 'FALLA';
update eventos set nombre_en='FIRE' where nombre= 'INCENDIO';
update eventos set nombre_en='FOREST FIRE' where nombre= 'FORESTAL';
update eventos set nombre_en='EXPLOSION' where nombre= 'EXPLOSION';
update eventos set nombre_en='LEAK' where nombre= 'ESCAPE';
update eventos set nombre_en='STRUCTURE' where nombre= 'ESTRUCTURA';
update eventos set nombre_en='PANIC' where nombre= 'PANICO';
update eventos set nombre_en='EPIDEMIC' where nombre= 'EPIDEMIA';
update eventos set nombre_en='PLAGUE' where nombre= 'PLAGA';
update eventos set nombre_en='ACCIDENT' where nombre= 'ACCIDENTE';
update eventos set nombre_en='OTHER' where nombre= 'OTROS';
update eventos set nombre_en='BIOLOGICAL' where nombre= 'BIOLOGICO';
update eventos set nombre_en='ERUPTION' where nombre= 'ERUPCION';
update eventos set nombre_en='CONTAMINATION' where nombre= 'CONTAMINACION';
update eventos set nombre_en='ELECTRIC STORM' where  nombre='TORMENTA E.';
update eventos set nombre_en='SNOWSTORM' where nombre= 'NEVADA';
update eventos set nombre_en='HEAT WAVE' where nombre='OLA DE CALOR' ;
update eventos set nombre_en='COLD WAVE'  where nombre= 'OLA DE FRIO';
update eventos set nombre_en='TORNADO' where nombre= 'TORNADO';
update eventos set nombre_en='FOG' where nombre= 'NEBLINA';
update eventos set nombre_en='INTOXICATION' where nombre= 'INTOXICACION';
update eventos set nombre_en='EPIZOOTIC' where nombre= 'EPIZOOTIA';
update eventos set nombre_en='FOG' where nombre= 'NIEBLA';
update eventos set nombre_en='ACCIDENT' where nombre= 'A. TRANSITO';
update eventos set nombre_en='ACCIDENT' where nombre= 'ACCIDENTE TRANS';
update eventos set nombre_en='FAMINE' where nombre= 'HAMBRUNA';
update eventos set nombre_en='STORM' where nombre= 'TORMENTA TROPIC';
update eventos set nombre_en='FAMINE' where nombre= 'RACIONAMIENTO';
update eventos set nombre_en='COLD WAVE'  where nombre= 'ONDA FRIA';



