//PACKAGE NAME
package org.lared.desinventar.webobject;

import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import java.text.*;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;

import org.lared.desinventar.util.*;
import org.lared.desinventar.system.*;
import org.lared.desinventar.webobject.*;


//CLASS NAME
// generated by WebObjectGenerator...

// WARNING:  manually customized!!!

public class fichas_base extends webObject
{
    
    // DATA MEMBERS OF THE CLASS. THEY ARE EXACT MAPPING OF DB. RECORD.
     public   String   serial;
     public   String   level0;
     public   String   level1;
     public   String   level2;
     public   String   name0;
     public   String   name1;
     public   String   name2;
     public   String   evento;
     public   String   lugar;
     public   int      fechano;
     public   int      fechames;
     public   int      fechadia;
     public   int      muertos;
     public   int      heridos;
     public   int      desaparece;
     public   int      afectados;
     public   int      vivdest;
     public   int      vivafec;
     public   String   otros;
     public   String   fuentes;
     public   double   valorloc;
     public   double   valorus;
     public   String   fechapor;
     public   String   fechafec;
     public   int      hay_muertos;
     public   int      hay_heridos;
     public   int      hay_deasparece;
     public   int      hay_afectados;
     public   int      hay_vivdest;
     public   int      hay_vivafec;
     public   int      hay_otros;
     public   int      socorro;
     public   int      salud;
     public   int      educacion;
     public   int      agropecuario;
     public   int      industrias;
     public   int      acueducto;
     public   int      alcantarillado;
     public   int      energia;
     public   int      comunicaciones;
     public   String   causa;
     public   String   descausa;
     public   int      transporte;
     public   String   magnitud2;
     public   int      nhospitales;
     public   int      nescuelas;
     public   double   nhectareas;
     public   int      cabezas;
     public   double   kmvias;
     public   int      duracion;
     public   int      damnificados;
     public   int      evacuados;
     public   int      hay_damnificados;
     public   int      hay_evacuados;
     public   int      hay_reubicados;
     public   int      reubicados;
     public   int      clave;
     public   String   glide;
	 public   int      defaultab;
	 public   int      approved;
	 public   double   latitude;
	 public   double   longitude;
	public 	String uu_id;
	public 	String di_comments;

	//--------------------------------------------------------------------------------
	// creates a hash table with field values of the data members
	//--------------------------------------------------------------------------------

  public void updateHashTable()
  {
		// FIELD NAMES VECTOR
		asFieldNames.put("serial", serial);
		asFieldNames.put("level0", level0);
		asFieldNames.put("level1", level1);
		asFieldNames.put("level2", level2);
		asFieldNames.put("name0", name0);
		asFieldNames.put("name1", name1);
		asFieldNames.put("name2", name2);
		asFieldNames.put("evento", evento);
		asFieldNames.put("lugar", lugar);
		asFieldNames.put("fechano", String.valueOf(fechano));
		asFieldNames.put("fechames", String.valueOf(fechames));
		asFieldNames.put("fechadia", String.valueOf(fechadia));
		asFieldNames.put("muertos", String.valueOf(muertos));
		asFieldNames.put("heridos", String.valueOf(heridos));
		asFieldNames.put("desaparece", String.valueOf(desaparece));
		asFieldNames.put("afectados", String.valueOf(afectados));
		asFieldNames.put("vivdest", String.valueOf(vivdest));
		asFieldNames.put("vivafec", String.valueOf(vivafec));
		asFieldNames.put("otros", otros);
		asFieldNames.put("fuentes", fuentes);
		asFieldNames.put("valorloc", String.valueOf(valorloc));
		asFieldNames.put("valorus", String.valueOf(valorus));
		asFieldNames.put("fechapor", fechapor);
		asFieldNames.put("fechafec", fechafec);
		asFieldNames.put("hay_muertos", String.valueOf(hay_muertos));
		asFieldNames.put("hay_heridos", String.valueOf(hay_heridos));
		asFieldNames.put("hay_deasparece", String.valueOf(hay_deasparece));
		asFieldNames.put("hay_afectados", String.valueOf(hay_afectados));
		asFieldNames.put("hay_vivdest", String.valueOf(hay_vivdest));
		asFieldNames.put("hay_vivafec", String.valueOf(hay_vivafec));
		asFieldNames.put("hay_otros", String.valueOf(hay_otros));
		asFieldNames.put("socorro", String.valueOf(socorro));
		asFieldNames.put("salud", String.valueOf(salud));
		asFieldNames.put("educacion", String.valueOf(educacion));
		asFieldNames.put("agropecuario", String.valueOf(agropecuario));
		asFieldNames.put("industrias", String.valueOf(industrias));
		asFieldNames.put("acueducto", String.valueOf(acueducto));
		asFieldNames.put("alcantarillado", String.valueOf(alcantarillado));
		asFieldNames.put("energia", String.valueOf(energia));
		asFieldNames.put("comunicaciones", String.valueOf(comunicaciones));
		asFieldNames.put("causa", causa);
		asFieldNames.put("descausa", descausa);
		asFieldNames.put("transporte", String.valueOf(transporte));
		asFieldNames.put("magnitud2", magnitud2);
		asFieldNames.put("nhospitales", String.valueOf(nhospitales));
		asFieldNames.put("nescuelas", String.valueOf(nescuelas));
		asFieldNames.put("nhectareas", String.valueOf(nhectareas));
		asFieldNames.put("cabezas", String.valueOf(cabezas));
		asFieldNames.put("kmvias", String.valueOf(kmvias));
		asFieldNames.put("duracion", String.valueOf(duracion));
		asFieldNames.put("damnificados", String.valueOf(damnificados));
		asFieldNames.put("evacuados", String.valueOf(evacuados));
		asFieldNames.put("hay_damnificados", String.valueOf(hay_damnificados));
		asFieldNames.put("hay_evacuados", String.valueOf(hay_evacuados));
		asFieldNames.put("hay_reubicados", String.valueOf(hay_reubicados));
		asFieldNames.put("reubicados", String.valueOf(reubicados));
		asFieldNames.put("clave", String.valueOf(clave));
		asFieldNames.put("glide", glide);
		asFieldNames.put("defaultab", String.valueOf(defaultab));
		asFieldNames.put("approved", String.valueOf(approved));
		asFieldNames.put("latitude", String.valueOf(latitude));
		asFieldNames.put("longitude", String.valueOf(longitude));
		asFieldNames.put("uu_id", uu_id);
		asFieldNames.put("di_comments", di_comments);

	}

	//--------------------------------------------------------------------------------
	// update data members with values stored in hash table
	//--------------------------------------------------------------------------------

	public void updateMembersFromHashTable() {
		// REVERSE FIELD NAMES VECTOR
		setSerial((String)asFieldNames.get("serial"));
		setLevel0((String)asFieldNames.get("level0"));
		setLevel1((String)asFieldNames.get("level1"));
		setLevel2((String)asFieldNames.get("level2"));
		setName0((String)asFieldNames.get("name0"));
		setName1((String)asFieldNames.get("name1"));
		setName2((String)asFieldNames.get("name2"));
		setEvento((String)asFieldNames.get("evento"));
		setLugar((String)asFieldNames.get("lugar"));
		setFechano((String)asFieldNames.get("fechano"));
		setFechames((String)asFieldNames.get("fechames"));
		setFechadia((String)asFieldNames.get("fechadia"));
		setMuertos((String)asFieldNames.get("muertos"));
		setHeridos((String)asFieldNames.get("heridos"));
		setDesaparece((String)asFieldNames.get("desaparece"));
		setAfectados((String)asFieldNames.get("afectados"));
		setVivdest((String)asFieldNames.get("vivdest"));
		setVivafec((String)asFieldNames.get("vivafec"));
		setOtros((String)asFieldNames.get("otros"));
		setFuentes((String)asFieldNames.get("fuentes"));
		setValorloc((String)asFieldNames.get("valorloc"));
		setValorus((String)asFieldNames.get("valorus"));
		setFechapor((String)asFieldNames.get("fechapor"));
		setFechafec((String)asFieldNames.get("fechafec"));
		setHay_muertos((String)asFieldNames.get("hay_muertos"));
		setHay_heridos((String)asFieldNames.get("hay_heridos"));
		setHay_deasparece((String)asFieldNames.get("hay_deasparece"));
		setHay_afectados((String)asFieldNames.get("hay_afectados"));
		setHay_vivdest((String)asFieldNames.get("hay_vivdest"));
		setHay_vivafec((String)asFieldNames.get("hay_vivafec"));
		setHay_otros((String)asFieldNames.get("hay_otros"));
		setSocorro((String)asFieldNames.get("socorro"));
		setSalud((String)asFieldNames.get("salud"));
		setEducacion((String)asFieldNames.get("educacion"));
		setAgropecuario((String)asFieldNames.get("agropecuario"));
		setIndustrias((String)asFieldNames.get("industrias"));
		setAcueducto((String)asFieldNames.get("acueducto"));
		setAlcantarillado((String)asFieldNames.get("alcantarillado"));
		setEnergia((String)asFieldNames.get("energia"));
		setComunicaciones((String)asFieldNames.get("comunicaciones"));
		setCausa((String)asFieldNames.get("causa"));
		setDescausa((String)asFieldNames.get("descausa"));
		setTransporte((String)asFieldNames.get("transporte"));
		setMagnitud2((String)asFieldNames.get("magnitud2"));
		setNhospitales((String)asFieldNames.get("nhospitales"));
		setNescuelas((String)asFieldNames.get("nescuelas"));
		setNhectareas((String)asFieldNames.get("nhectareas"));
		setCabezas((String)asFieldNames.get("cabezas"));
		setKmvias((String)asFieldNames.get("kmvias"));
		setDuracion((String)asFieldNames.get("duracion"));
		setDamnificados((String)asFieldNames.get("damnificados"));
		setEvacuados((String)asFieldNames.get("evacuados"));
		setHay_damnificados((String)asFieldNames.get("hay_damnificados"));
		setHay_evacuados((String)asFieldNames.get("hay_evacuados"));
		setHay_reubicados((String)asFieldNames.get("hay_reubicados"));
		setReubicados((String)asFieldNames.get("reubicados"));
		setClave((String)asFieldNames.get("clave"));
		setGlide((String)asFieldNames.get("glide"));
		setDefaultab((String)asFieldNames.get("defaultab"));
		setApproved((String)asFieldNames.get("approved"));
		setLatitude((String)asFieldNames.get("latitude"));
		setLongitude((String)asFieldNames.get("longitude"));
		setUu_id((String)asFieldNames.get("uu_id"));
		setDi_comments((String)asFieldNames.get("di_comments"));

	}


	//--------------------------------------------------------------------------------
	// constructor of the class. it initializes the object variables
	//--------------------------------------------------------------------------------

	// CONSTRUCTOR
	public void init()
	{
		lastError="No errors detected";
		serial = "";
		level0 = "";
		level1 = "";
		level2 = "";
		name0 = "";
		name1 = "";
		name2 = "";
		evento = "";
		lugar = "";
		fechano = 0;
		fechames = 0;
		fechadia = 0;
		muertos = 0;
		heridos = 0;
		desaparece = 0;
		afectados = 0;
		vivdest = 0;
		vivafec = 0;
		otros = "";
		fuentes = "";
		valorloc = 0;
		valorus = 0;
		fechapor = "";
		fechafec = "";
		hay_muertos = 0;
		hay_heridos = 0;
		hay_deasparece = 0;
		hay_afectados = 0;
		hay_vivdest = 0;
		hay_vivafec = 0;
		hay_otros = 0;
		socorro = 0;
		salud = 0;
		educacion = 0;
		agropecuario = 0;
		industrias = 0;
		acueducto = 0;
		alcantarillado = 0;
		energia = 0;
		comunicaciones = 0;
		causa = "";
		descausa = "";
		transporte = 0;
		magnitud2 = "";
		nhospitales = 0;
		nescuelas = 0;
		nhectareas = 0;
		cabezas = 0;
		kmvias = 0;
		duracion = 0;
		damnificados = 0;
		evacuados = 0;
		hay_damnificados = 0;
		hay_evacuados = 0;
		hay_reubicados = 0;
		reubicados = 0;
		clave = 0;
		glide = "";
		defaultab = 0;
		approved = 0;
		latitude = 0;
		longitude = 0;
		uu_id = "";
		di_comments = "";
		updateHashTable();
	}

	public fichas_base()
	{
		super("fichas object");
		init();
	}
//--------------------------------------------------------------------------------
// getter and setter methods of the elements of the class
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// METHODS FOR: serial
	public String getSerial()
	{
		return serial;
	}

	public void setSerial(String sParameter)
	{
		serial = sParameter;
	}
// end of methods for Serial
//--------------------------------------------------------------------------------
// METHODS FOR: level0
	public String getLevel0()
	{
		return level0;
	}

	public void setLevel0(String sParameter)
	{
		level0 = sParameter;
	}
// end of methods for Level0
//--------------------------------------------------------------------------------
// METHODS FOR: level1
	public String getLevel1()
	{
		return level1;
	}

	public void setLevel1(String sParameter)
	{
		level1 = sParameter;
	}
// end of methods for Level1
//--------------------------------------------------------------------------------
// METHODS FOR: level2
	public String getLevel2()
	{
		return level2;
	}

	public void setLevel2(String sParameter)
	{
		level2 = sParameter;
	}
// end of methods for Level2
//--------------------------------------------------------------------------------
// METHODS FOR: name0
	public String getName0()
	{
		return name0;
	}

	public void setName0(String sParameter)
	{
		name0 = sParameter;
	}
// end of methods for Name0
//--------------------------------------------------------------------------------
// METHODS FOR: name1
	public String getName1()
	{
		return name1;
	}

	public void setName1(String sParameter)
	{
		name1 = sParameter;
	}
// end of methods for Name1
//--------------------------------------------------------------------------------
// METHODS FOR: name2
	public String getName2()
	{
		return name2;
	}

	public void setName2(String sParameter)
	{
		name2 = sParameter;
	}
// end of methods for Name2
//--------------------------------------------------------------------------------
// METHODS FOR: evento
	public String getEvento()
	{
		return evento;
	}

	public void setEvento(String sParameter)
	{
		evento = sParameter;
	}
// end of methods for Evento
//--------------------------------------------------------------------------------
// METHODS FOR: lugar
	public String getLugar()
	{
		return lugar;
	}

	public void setLugar(String sParameter)
	{
		lugar = sParameter;
	}
// end of methods for Lugar
//--------------------------------------------------------------------------------
// METHODS FOR: fechano
	public String getFechano()
	{
		return Integer.toString(fechano);
	}

	public void setFechano(String sParameter)
	{
		fechano = extendedParseInt(sParameter);
	}
// end of methods for Fechano
//--------------------------------------------------------------------------------
// METHODS FOR: fechames
	public String getFechames()
	{
		return Integer.toString(fechames);
	}

	public void setFechames(String sParameter)
	{
		fechames = extendedParseInt(sParameter);
	}
// end of methods for Fechames
//--------------------------------------------------------------------------------
// METHODS FOR: fechadia
	public String getFechadia()
	{
		return Integer.toString(fechadia);
	}

	public void setFechadia(String sParameter)
	{
		fechadia = extendedParseInt(sParameter);
	}
// end of methods for Fechadia
//--------------------------------------------------------------------------------
// METHODS FOR: muertos
	public String getMuertos()
	{
		return Integer.toString(muertos);
	}

	public void setMuertos(String sParameter)
	{
		muertos = extendedParseInt(sParameter);
	}
// end of methods for Muertos
//--------------------------------------------------------------------------------
// METHODS FOR: heridos
	public String getHeridos()
	{
		return Integer.toString(heridos);
	}

	public void setHeridos(String sParameter)
	{
		heridos = extendedParseInt(sParameter);
	}
// end of methods for Heridos
//--------------------------------------------------------------------------------
// METHODS FOR: desaparece
	public String getDesaparece()
	{
		return Integer.toString(desaparece);
	}

	public void setDesaparece(String sParameter)
	{
		desaparece = extendedParseInt(sParameter);
	}
// end of methods for Desaparece
//--------------------------------------------------------------------------------
// METHODS FOR: afectados
	public String getAfectados()
	{
		return Integer.toString(afectados);
	}

	public void setAfectados(String sParameter)
	{
		afectados = extendedParseInt(sParameter);
	}
// end of methods for Afectados
//--------------------------------------------------------------------------------
// METHODS FOR: vivdest
	public String getVivdest()
	{
		return Integer.toString(vivdest);
	}

	public void setVivdest(String sParameter)
	{
		vivdest = extendedParseInt(sParameter);
	}
// end of methods for Vivdest
//--------------------------------------------------------------------------------
// METHODS FOR: vivafec
	public String getVivafec()
	{
		return Integer.toString(vivafec);
	}

	public void setVivafec(String sParameter)
	{
		vivafec = extendedParseInt(sParameter);
	}
// end of methods for Vivafec
//--------------------------------------------------------------------------------
// METHODS FOR: otros
	public String getOtros()
	{
		return otros;
	}

	public void setOtros(String sParameter)
	{
		otros = sParameter;
	}
// end of methods for Otros
//--------------------------------------------------------------------------------
// METHODS FOR: fuentes
	public String getFuentes()
	{
		return fuentes;
	}

	public void setFuentes(String sParameter)
	{
		fuentes = sParameter;
	}
// end of methods for Fuentes
//--------------------------------------------------------------------------------
// METHODS FOR: valorloc
	public String getValorloc()
	{
		return Double.toString(valorloc);
	}

	public void setValorloc(String sParameter)
	{
		valorloc = extendedParseDouble(sParameter);
	}
// end of methods for Valorloc
//--------------------------------------------------------------------------------
// METHODS FOR: valorus
	public String getValorus()
	{
		return Double.toString(valorus);
	}

	public void setValorus(String sParameter)
	{
		valorus = extendedParseDouble(sParameter);
	}
// end of methods for Valorus
//--------------------------------------------------------------------------------
// METHODS FOR: fechapor
	public String getFechapor()
	{
		return fechapor;
	}

	public void setFechapor(String sParameter)
	{
		fechapor = sParameter;
	}
// end of methods for Fechapor
//--------------------------------------------------------------------------------
// METHODS FOR: fechafec
	public String getFechafec()
	{
		return fechafec;
	}

	public void setFechafec(String sParameter)
	{
		fechafec = sParameter;
	}
// end of methods for Fechafec
//--------------------------------------------------------------------------------
// METHODS FOR: hay_muertos
	public String getHay_muertos()
	{
		return Integer.toString(hay_muertos);
	}

	public void setHay_muertos(String sParameter)
	{
		hay_muertos = extendedParseInt(sParameter);
	}
// end of methods for Hay_muertos
//--------------------------------------------------------------------------------
// METHODS FOR: hay_heridos
	public String getHay_heridos()
	{
		return Integer.toString(hay_heridos);
	}

	public void setHay_heridos(String sParameter)
	{
		hay_heridos = extendedParseInt(sParameter);
	}
// end of methods for Hay_heridos
//--------------------------------------------------------------------------------
// METHODS FOR: hay_deasparece
	public String getHay_deasparece()
	{
		return Integer.toString(hay_deasparece);
	}

	public void setHay_deasparece(String sParameter)
	{
		hay_deasparece = extendedParseInt(sParameter);
	}
// end of methods for Hay_deasparece
//--------------------------------------------------------------------------------
// METHODS FOR: hay_afectados
	public String getHay_afectados()
	{
		return Integer.toString(hay_afectados);
	}

	public void setHay_afectados(String sParameter)
	{
		hay_afectados = extendedParseInt(sParameter);
	}
// end of methods for Hay_afectados
//--------------------------------------------------------------------------------
// METHODS FOR: hay_vivdest
	public String getHay_vivdest()
	{
		return Integer.toString(hay_vivdest);
	}

	public void setHay_vivdest(String sParameter)
	{
		hay_vivdest = extendedParseInt(sParameter);
	}
// end of methods for Hay_vivdest
//--------------------------------------------------------------------------------
// METHODS FOR: hay_vivafec
	public String getHay_vivafec()
	{
		return Integer.toString(hay_vivafec);
	}

	public void setHay_vivafec(String sParameter)
	{
		hay_vivafec = extendedParseInt(sParameter);
	}
// end of methods for Hay_vivafec
//--------------------------------------------------------------------------------
// METHODS FOR: hay_otros
	public String getHay_otros()
	{
		return Integer.toString(hay_otros);
	}

	public void setHay_otros(String sParameter)
	{
		hay_otros = extendedParseInt(sParameter);
	}
// end of methods for Hay_otros
//--------------------------------------------------------------------------------
// METHODS FOR: socorro
	public String getSocorro()
	{
		return Integer.toString(socorro);
	}

	public void setSocorro(String sParameter)
	{
		socorro = extendedParseInt(sParameter);
	}
// end of methods for Socorro
//--------------------------------------------------------------------------------
// METHODS FOR: salud
	public String getSalud()
	{
		return Integer.toString(salud);
	}

	public void setSalud(String sParameter)
	{
		salud = extendedParseInt(sParameter);
	}
// end of methods for Salud
//--------------------------------------------------------------------------------
// METHODS FOR: educacion
	public String getEducacion()
	{
		return Integer.toString(educacion);
	}

	public void setEducacion(String sParameter)
	{
		educacion = extendedParseInt(sParameter);
	}
// end of methods for Educacion
//--------------------------------------------------------------------------------
// METHODS FOR: agropecuario
	public String getAgropecuario()
	{
		return Integer.toString(agropecuario);
	}

	public void setAgropecuario(String sParameter)
	{
		agropecuario = extendedParseInt(sParameter);
	}
// end of methods for Agropecuario
//--------------------------------------------------------------------------------
// METHODS FOR: industrias
	public String getIndustrias()
	{
		return Integer.toString(industrias);
	}

	public void setIndustrias(String sParameter)
	{
		industrias = extendedParseInt(sParameter);
	}
// end of methods for Industrias
//--------------------------------------------------------------------------------
// METHODS FOR: acueducto
	public String getAcueducto()
	{
		return Integer.toString(acueducto);
	}

	public void setAcueducto(String sParameter)
	{
		acueducto = extendedParseInt(sParameter);
	}
// end of methods for Acueducto
//--------------------------------------------------------------------------------
// METHODS FOR: alcantarillado
	public String getAlcantarillado()
	{
		return Integer.toString(alcantarillado);
	}

	public void setAlcantarillado(String sParameter)
	{
		alcantarillado = extendedParseInt(sParameter);
	}
// end of methods for Alcantarillado
//--------------------------------------------------------------------------------
// METHODS FOR: energia
	public String getEnergia()
	{
		return Integer.toString(energia);
	}

	public void setEnergia(String sParameter)
	{
		energia = extendedParseInt(sParameter);
	}
// end of methods for Energia
//--------------------------------------------------------------------------------
// METHODS FOR: comunicaciones
	public String getComunicaciones()
	{
		return Integer.toString(comunicaciones);
	}

	public void setComunicaciones(String sParameter)
	{
		comunicaciones = extendedParseInt(sParameter);
	}
// end of methods for Comunicaciones
//--------------------------------------------------------------------------------
// METHODS FOR: causa
	public String getCausa()
	{
		return causa;
	}

	public void setCausa(String sParameter)
	{
		causa = sParameter;
	}
// end of methods for Causa
//--------------------------------------------------------------------------------
// METHODS FOR: descausa
	public String getDescausa()
	{
		return descausa;
	}

	public void setDescausa(String sParameter)
	{
		descausa = sParameter;
	}
// end of methods for Descausa
//--------------------------------------------------------------------------------
// METHODS FOR: transporte
	public String getTransporte()
	{
		return Integer.toString(transporte);
	}

	public void setTransporte(String sParameter)
	{
		transporte = extendedParseInt(sParameter);
	}
// end of methods for Transporte
//--------------------------------------------------------------------------------
// METHODS FOR: magnitud2
	public String getMagnitud2()
	{
		return magnitud2;
	}

	public void setMagnitud2(String sParameter)
	{
		magnitud2 = sParameter;
	}
// end of methods for Magnitud2
//--------------------------------------------------------------------------------
// METHODS FOR: nhospitales
	public String getNhospitales()
	{
		return Integer.toString(nhospitales);
	}

	public void setNhospitales(String sParameter)
	{
		nhospitales = extendedParseInt(sParameter);
	}
// end of methods for Nhospitales
//--------------------------------------------------------------------------------
// METHODS FOR: nescuelas
	public String getNescuelas()
	{
		return Integer.toString(nescuelas);
	}

	public void setNescuelas(String sParameter)
	{
		nescuelas = extendedParseInt(sParameter);
	}
// end of methods for Nescuelas
//--------------------------------------------------------------------------------
// METHODS FOR: nhectareas
	public String getNhectareas()
	{
		return Double.toString(nhectareas);
	}

	public void setNhectareas(String sParameter)
	{
		nhectareas = extendedParseDouble(sParameter);
	}
// end of methods for Nhectareas
//--------------------------------------------------------------------------------
// METHODS FOR: cabezas
	public String getCabezas()
	{
		return Integer.toString(cabezas);
	}

	public void setCabezas(String sParameter)
	{
		cabezas = extendedParseInt(sParameter);
	}
// end of methods for Cabezas
//--------------------------------------------------------------------------------
// METHODS FOR: kmvias
	public String getKmvias()
	{
		return Double.toString(kmvias);
	}

	public void setKmvias(String sParameter)
	{
		kmvias = extendedParseDouble(sParameter);
	}
// end of methods for Kmvias
//--------------------------------------------------------------------------------
// METHODS FOR: duracion
	public String getDuracion()
	{
		return Integer.toString(duracion);
	}

	public void setDuracion(String sParameter)
	{
		duracion = extendedParseInt(sParameter);
	}
// end of methods for Duracion
//--------------------------------------------------------------------------------
// METHODS FOR: damnificados
	public String getDamnificados()
	{
		return Integer.toString(damnificados);
	}

	public void setDamnificados(String sParameter)
	{
		damnificados = extendedParseInt(sParameter);
	}
// end of methods for Damnificados
//--------------------------------------------------------------------------------
// METHODS FOR: evacuados
	public String getEvacuados()
	{
		return Integer.toString(evacuados);
	}

	public void setEvacuados(String sParameter)
	{
		evacuados = extendedParseInt(sParameter);
	}
// end of methods for Evacuados
//--------------------------------------------------------------------------------
// METHODS FOR: hay_damnificados
	public String getHay_damnificados()
	{
		return Integer.toString(hay_damnificados);
	}

	public void setHay_damnificados(String sParameter)
	{
		hay_damnificados = extendedParseInt(sParameter);
	}
// end of methods for Hay_damnificados
//--------------------------------------------------------------------------------
// METHODS FOR: hay_evacuados
	public String getHay_evacuados()
	{
		return Integer.toString(hay_evacuados);
	}

	public void setHay_evacuados(String sParameter)
	{
		hay_evacuados = extendedParseInt(sParameter);
	}
// end of methods for Hay_evacuados
//--------------------------------------------------------------------------------
// METHODS FOR: hay_reubicados
	public String getHay_reubicados()
	{
		return Integer.toString(hay_reubicados);
	}

	public void setHay_reubicados(String sParameter)
	{
		hay_reubicados = extendedParseInt(sParameter);
	}
// end of methods for Hay_reubicados
//--------------------------------------------------------------------------------
// METHODS FOR: reubicados
	public String getReubicados()
	{
		return Integer.toString(reubicados);
	}

	public void setReubicados(String sParameter)
	{
		reubicados = extendedParseInt(sParameter);
	}
// end of methods for Reubicados
//--------------------------------------------------------------------------------
// METHODS FOR: clave
	public String getClave()
	{
		return Integer.toString(clave);
	}

	public void setClave(String sParameter)
	{
		clave = extendedParseInt(sParameter);
	}
// end of methods for Clave
//--------------------------------------------------------------------------------
// METHODS FOR: glide
	public String getGlide()
	{
		return glide;
	}

	public void setGlide(String sParameter)
	{
		glide = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'defaultab'
	public String getDefaultab() {
		return Integer.toString(defaultab);
	}

	public void setDefaultab(String sParameter) {
		defaultab = extendedParseInt(sParameter);
	}

	public void setDefaultab(int sParameter) {
		defaultab = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'approved'
	public String getApproved() {
		return Integer.toString(approved);
	}

	public void setApproved(String sParameter) {
		approved = extendedParseInt(sParameter);
	}

	public void setApproved(int sParameter) {
		approved = sParameter;
	}
//--------------------------------------------------------------------------------
//--------------------------------------------------------------------------------
// Access methods for database field 'latitude'
	public String getLatitude() {
		return Double.toString(latitude);
	}

	public void setLatitude(String sParameter) {
		latitude = extendedParseDouble(sParameter);
	}

	public void setLatitude(double sParameter) {
		latitude = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'longitude'
	public String getLongitude() {
		return Double.toString(longitude);
	}

	public void setLongitude(String sParameter) {
		longitude = extendedParseDouble(sParameter);
	}

	public void setLongitude(double sParameter) {
		longitude = sParameter;
	}

//--------------------------------------------------------------------------------
// Access methods for database field 'uu_id'
	public String getUu_id() {
		return uu_id;
	}

	public void setUu_id(String sParameter) {
		uu_id = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'di_comments'
	public String getDi_comments() {
		return di_comments;
	}

	public void setDi_comments(String sParameter) {
		di_comments = sParameter;
	}
//--------------------------------------------------------------------------------

	//----------------------------------------------------------------
	// Operational methods any webObject must have. Abstract class
	// provides templates and default behaviour (return error)
	//----------------------------------------------------------------

	//--------------------------------------------------------------------------------
	// retrieves object info from HTML form fields
	//--------------------------------------------------------------------------------
	public int getForm(HttpServletRequest req, HttpServletResponse resp, Connection con) {

		// GET_FORM()
		serial = not_null(req.getParameter(assignName("serial")));
		level0 = not_null(req.getParameter(assignName("level0")));
		level1 = not_null(req.getParameter(assignName("level1")));
		level2 = not_null(req.getParameter(assignName("level2")));
		name0 = not_null(req.getParameter(assignName("name0")));
		name1 = not_null(req.getParameter(assignName("name1")));
		name2 = not_null(req.getParameter(assignName("name2")));
		evento = not_null(req.getParameter(assignName("evento")));
		lugar = not_null(req.getParameter(assignName("lugar")));
		fechano = extendedParseInt(req.getParameter(assignName("fechano")));
		fechames = extendedParseInt(req.getParameter(assignName("fechames")));
		fechadia = extendedParseInt(req.getParameter(assignName("fechadia")));
		muertos = extendedParseInt(req.getParameter(assignName("muertos")));
		heridos = extendedParseInt(req.getParameter(assignName("heridos")));
		desaparece = extendedParseInt(req.getParameter(assignName("desaparece")));
		afectados = extendedParseInt(req.getParameter(assignName("afectados")));
		vivdest = extendedParseInt(req.getParameter(assignName("vivdest")));
		vivafec = extendedParseInt(req.getParameter(assignName("vivafec")));
		otros = not_null(req.getParameter(assignName("otros")));
		fuentes = not_null(req.getParameter(assignName("fuentes")));
		valorloc = extendedParseDouble(req.getParameter(assignName("valorloc")));
		valorus = extendedParseDouble(req.getParameter(assignName("valorus")));
		fechapor = not_null(req.getParameter(assignName("fechapor")));
		fechafec = not_null(req.getParameter(assignName("fechafec")));
		hay_muertos = extendedParseInt(req.getParameter(assignName("hay_muertos")));
		hay_heridos = extendedParseInt(req.getParameter(assignName("hay_heridos")));
		hay_deasparece = extendedParseInt(req.getParameter(assignName("hay_deasparece")));
		hay_afectados = extendedParseInt(req.getParameter(assignName("hay_afectados")));
		hay_vivdest = extendedParseInt(req.getParameter(assignName("hay_vivdest")));
		hay_vivafec = extendedParseInt(req.getParameter(assignName("hay_vivafec")));
		hay_otros = extendedParseInt(req.getParameter(assignName("hay_otros")));
		socorro = extendedParseInt(req.getParameter(assignName("socorro")));
		salud = extendedParseInt(req.getParameter(assignName("salud")));
		educacion = extendedParseInt(req.getParameter(assignName("educacion")));
		agropecuario = extendedParseInt(req.getParameter(assignName("agropecuario")));
		industrias = extendedParseInt(req.getParameter(assignName("industrias")));
		acueducto = extendedParseInt(req.getParameter(assignName("acueducto")));
		alcantarillado = extendedParseInt(req.getParameter(assignName("alcantarillado")));
		energia = extendedParseInt(req.getParameter(assignName("energia")));
		comunicaciones = extendedParseInt(req.getParameter(assignName("comunicaciones")));
		causa = not_null(req.getParameter(assignName("causa")));
		descausa = not_null(req.getParameter(assignName("descausa")));
		transporte = extendedParseInt(req.getParameter(assignName("transporte")));
		magnitud2 = not_null(req.getParameter(assignName("magnitud2")));
		nhospitales = extendedParseInt(req.getParameter(assignName("nhospitales")));
		nescuelas = extendedParseInt(req.getParameter(assignName("nescuelas")));
		nhectareas = extendedParseDouble(req.getParameter(assignName("nhectareas")));
		cabezas = extendedParseInt(req.getParameter(assignName("cabezas")));
		kmvias = extendedParseDouble(req.getParameter(assignName("kmvias")));
		duracion = extendedParseInt(req.getParameter(assignName("duracion")));
		damnificados = extendedParseInt(req.getParameter(assignName("damnificados")));
		evacuados = extendedParseInt(req.getParameter(assignName("evacuados")));
		hay_damnificados = extendedParseInt(req.getParameter(assignName("hay_damnificados")));
		hay_evacuados = extendedParseInt(req.getParameter(assignName("hay_evacuados")));
		hay_reubicados = extendedParseInt(req.getParameter(assignName("hay_reubicados")));
		reubicados = extendedParseInt(req.getParameter(assignName("reubicados")));
		clave = extendedParseInt(req.getParameter(assignName("clave")));
		glide = not_null(req.getParameter(assignName("glide")));
		defaultab=extendedParseInt(req.getParameter(assignName("defaultab")));
		approved=extendedParseInt(req.getParameter(assignName("approved")));
		latitude=extendedParseDouble(req.getParameter(assignName("latitude")));
		longitude=extendedParseDouble(req.getParameter(assignName("longitude")));
		setUu_id(not_null(req.getParameter(assignName("uu_id"))));
		setDi_comments(not_null(req.getParameter(assignName("di_comments"))));

		updateHashTable();
		return 0;
	}

	//--------------------------------------------------------------------------------
	// loads an object from a record read from database
	//--------------------------------------------------------------------------------
  public void loadWebObject(ResultSet rset)
    {
		try {
			// SQL_LOAD

			try {
				serial = not_null(rset.getString("serial"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field serial -->";
				System.out.println(ex.toString());
			}

			try {
				level0 = not_null(rset.getString("level0"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field level0 -->";
				System.out.println(ex.toString());
			}

			try {
				level1 = not_null(rset.getString("level1"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field level1 -->";
				System.out.println(ex.toString());
			}

			try {
				level2 = not_null(rset.getString("level2"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field level2 -->";
				System.out.println(ex.toString());
			}

			try {
				name0 = not_null(rset.getString("name0"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field name0 -->";
				System.out.println(ex.toString());
			}

			try {
				name1 = not_null(rset.getString("name1"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field name1 -->";
				System.out.println(ex.toString());
			}

			try {
				name2 = not_null(rset.getString("name2"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field name2 -->";
				System.out.println(ex.toString());
			}

			try {
				evento = not_null(rset.getString("evento"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field evento -->";
				System.out.println(ex.toString());
			}

			try {
				lugar = not_null(rset.getString("lugar"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field lugar -->";
				System.out.println(ex.toString());
			}

			try {
				fechano = rset.getInt("fechano");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fechano -->";
				System.out.println(ex.toString());
			}

			try {
				fechames = rset.getInt("fechames");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fechames -->";
				System.out.println(ex.toString());
			}

			try {
				fechadia = rset.getInt("fechadia");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fechadia -->";
				System.out.println(ex.toString());
			}

			try {
				muertos = rset.getInt("muertos");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field muertos -->";
				System.out.println(ex.toString());
			}

			try {
				heridos = rset.getInt("heridos");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field heridos -->";
				System.out.println(ex.toString());
			}

			try {
				desaparece = rset.getInt("desaparece");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field desaparece -->";
				System.out.println(ex.toString());
			}

			try {
				afectados = rset.getInt("afectados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field afectados -->";
				System.out.println(ex.toString());
			}

			try {
				vivdest = rset.getInt("vivdest");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field vivdest -->";
				System.out.println(ex.toString());
			}

			try {
				vivafec = rset.getInt("vivafec");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field vivafec -->";
				System.out.println(ex.toString());
			}

			try {
				otros = not_null(rset.getString("otros"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field otros -->";
				System.out.println(ex.toString());
			}


			try {
				fuentes = not_null(rset.getString("fuentes"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fuentes -->";
				System.out.println(ex.toString());
			}

			try {
				valorloc = rset.getDouble("valorloc");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field valorloc -->";
				System.out.println(ex.toString());
			}

			try {
				valorus = rset.getDouble("valorus");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field valorus -->";
				System.out.println(ex.toString());
			}

			try {
				fechapor = not_null(rset.getString("fechapor"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fechapor -->";
				System.out.println(ex.toString());
			}

			try {
				fechafec = not_null(rset.getString("fechafec"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field fechafec -->";
				System.out.println(ex.toString());
			}

			try {
				hay_muertos = rset.getInt("hay_muertos");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_muertos -->";
				System.out.println(ex.toString());
			}

			try {
				hay_heridos = rset.getInt("hay_heridos");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_heridos -->";
				System.out.println(ex.toString());
			}

			try {
				hay_deasparece = rset.getInt("hay_deasparece");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_deasparece -->";
				System.out.println(ex.toString());
			}

			try {
				hay_afectados = rset.getInt("hay_afectados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_afectados -->";
				System.out.println(ex.toString());
			}

			try {
				hay_vivdest = rset.getInt("hay_vivdest");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_vivdest -->";
				System.out.println(ex.toString());
			}

			try {
				hay_vivafec = rset.getInt("hay_vivafec");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_vivafec -->";
				System.out.println(ex.toString());
			}

			try {
				hay_otros = rset.getInt("hay_otros");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_otros -->";
				System.out.println(ex.toString());
			}

			try {
				socorro = rset.getInt("socorro");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field socorro -->";
				System.out.println(ex.toString());
			}

			try {
				salud = rset.getInt("salud");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field salud -->";
				System.out.println(ex.toString());
			}

			try {
				educacion = rset.getInt("educacion");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field educacion -->";
				System.out.println(ex.toString());
			}

			try {
				agropecuario = rset.getInt("agropecuario");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field agropecuario -->";
				System.out.println(ex.toString());
			}

			try {
				industrias = rset.getInt("industrias");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field industrias -->";
				System.out.println(ex.toString());
			}

			try {
				acueducto = rset.getInt("acueducto");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field acueducto -->";
				System.out.println(ex.toString());
			}

			try {
				alcantarillado = rset.getInt("alcantarillado");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field alcantarillado -->";
				System.out.println(ex.toString());
			}

			try {
				energia = rset.getInt("energia");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field energia -->";
				System.out.println(ex.toString());
			}

			try {
				comunicaciones = rset.getInt("comunicaciones");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field comunicaciones -->";
				System.out.println(ex.toString());
			}

			try {
				causa = not_null(rset.getString("causa"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field causa -->";
				System.out.println(ex.toString());
			}

			try {
				descausa = not_null(rset.getString("descausa"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field descausa -->";
				System.out.println(ex.toString());
			}

			try {
				transporte = rset.getInt("transporte");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field transporte -->";
				System.out.println(ex.toString());
			}

			try {
				magnitud2 = not_null(rset.getString("magnitud2"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field magnitud2 -->";
				System.out.println(ex.toString());
			}

			try {
				nhospitales = rset.getInt("nhospitales");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field nhospitales -->";
				System.out.println(ex.toString());
			}

			try {
				nescuelas = rset.getInt("nescuelas");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field nescuelas -->";
				System.out.println(ex.toString());
			}

			try {
				nhectareas = rset.getDouble("nhectareas");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field nhectareas -->";
				System.out.println(ex.toString());
			}

			try {
				cabezas = rset.getInt("cabezas");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field cabezas -->";
				System.out.println(ex.toString());
			}

			try {
				kmvias = rset.getDouble("kmvias");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field kmvias -->";
				System.out.println(ex.toString());
			}


			try {
				duracion = rset.getInt("duracion");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field duracion -->";
				System.out.println(ex.toString());
			}

			try {
				damnificados = rset.getInt("damnificados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field damnificados -->";
				System.out.println(ex.toString());
			}

			try {
				evacuados = rset.getInt("evacuados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field evacuados -->";
				System.out.println(ex.toString());
			}

			try {
				hay_damnificados = rset.getInt("hay_damnificados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_damnificados -->";
				System.out.println(ex.toString());
			}

			try {
				hay_evacuados = rset.getInt("hay_evacuados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_evacuados -->";
				System.out.println(ex.toString());
			}

			try {
				hay_reubicados = rset.getInt("hay_reubicados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field hay_reubicados -->";
				System.out.println(ex.toString());
			}

			try {
				reubicados = rset.getInt("reubicados");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field reubicados -->";
				System.out.println(ex.toString());
			}

			try {
				clave = rset.getInt("clave");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field clave -->";
				System.out.println(ex.toString());
			}

			try {
				glide = not_null(rset.getString("glide"));
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field glide -->";
				// System.out.println(ex.toString());
			}

			try {
				defaultab = rset.getInt("defaultab");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field defaultab -->";
				// System.out.println(ex.toString());
			}

			try {
				approved = rset.getInt("approved");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field approved -->";
				// System.out.println(ex.toString());
			}

			try {
				latitude = rset.getDouble("latitude");

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field latitude -->";
				// System.out.println(ex.toString());
			}

			try {
				longitude = rset.getDouble("longitude");

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field longitude -->";
				// System.out.println(ex.toString());
			}

			try {
				uu_id = not_null(rset.getString("uu_id"));

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field uu_id -->";
				//System.out.println(ex.toString());
			}

			try {
				di_comments = this.getClob(rset,"di_comments");
			} catch (Exception ex) {
				lastError = "<-- error attempting to access field di_comments -->";
				// System.out.println(ex.toString());
			}

		} catch (Exception e) {
			lastError = "<!-- Error loading WebObject: " + e.toString() + " : " + sSql + " -->";
		}
		updateHashTable();
	}

	//--------------------------------------------------------------------------------
	// reads an object from the database
	//--------------------------------------------------------------------------------
  public int getWebObject(Connection con)
    {
		try {		
			// SQL_GET
			int f=1;
			sSql = "SELECT serial,level0,level1,level2,name0,name1,name2,evento,lugar,fechano,fechames,fechadia,muertos,heridos," +
					"desaparece,afectados,vivdest,vivafec,otros,fuentes,valorloc,valorus,fechapor,fechafec," +
					"hay_muertos,hay_heridos,hay_deasparece,hay_afectados,hay_vivdest,hay_vivafec,hay_otros," +
					"socorro,salud,educacion,agropecuario,industrias,acueducto,alcantarillado,energia,comunicaciones," +
					"causa,descausa,transporte,magnitud2,nhospitales,nescuelas,nhectareas,cabezas,kmvias," +
					"duracion,damnificados,evacuados,hay_damnificados,hay_evacuados,hay_reubicados,reubicados,clave," +
					"glide,defaultab,approved, latitude, longitude, di_comments, uu_id FROM fichas";
			sSql += " WHERE (clave = ?)";
			pstmt = con.prepareStatement(sSql);

			pstmt.setInt(f++, clave);


			rset = pstmt.executeQuery();
			int nrows = 1;
			if (rset.next())
				loadWebObject(rset);
			else
				nrows = 0;
			// releases the statement object
			rset.close();
			pstmt.close();
			lastError = ""; // "NO ERROR. sql="+sSql;
			return nrows;
		} catch (Exception ex) {
			//Trap and report SQL errors
			lastError = "<!-- Error getting webObject: " + ex.toString() + " : " + sSql
					+ " -->";
		}
		finally {
			// releases the statement object
			try { pstmt.close(); } catch (Exception ignrd) {}
		}

		return -1;
	}

	/**--------------------------------------------------------------------------------
	// checks the lengths of strings are <= to what is defined in the database
	//--------------------------------------------------------------------------------
	*/
	public void checkLengths()
    {
		// CHECK_LENGTHS
		if (this.serial.length()>15)
			serial=serial.substring(0,15);
		if (level0.length()>15)
			level0=level0.substring(0,15);
		if (level1.length()>15)
			level1=level1.substring(0,15);
		if (level2.length()>15)
			level2=level2.substring(0,15);
		if (name0.length()>30)
			name0=name0.substring(0,30);
		if (name1.length()>30)
			name1=name1.substring(0,30);
		if (name2.length()>30)
			name2=name2.substring(0,30);
		if (evento.length()>30)
			evento=evento.substring(0,30);
		if (lugar.length()>60)
			lugar=lugar.substring(0,60);
		if (otros.length()>60)
			otros=otros.substring(0,60);
		if (fuentes.length()>255)
			fuentes=fuentes.substring(0,255);
		if (fechapor.length()>12)
			fechapor=fechapor.substring(0,12);
		if (fechafec.length()>12)
			fechafec=fechafec.substring(0,12);
		if (causa.length()>25)
			causa=causa.substring(0,25);
		if (descausa.length()>60)
			descausa=descausa.substring(0,60);
		if (magnitud2.length()>25)
			magnitud2=magnitud2.substring(0,25);
		if (glide.length()>30)
			glide=glide.substring(0,30);
		if (uu_id.length()>37)
			uu_id=uu_id.substring(0,37);
		if (di_comments.length()>32767)
			di_comments=di_comments.substring(0,32767);
    }



	//--------------------------------------------------------------------------------
	// adds a new object to the database
	//--------------------------------------------------------------------------------
  public int addWebObject(Connection con)
    {
		try {
			// SQL_INSERT
			int f=1;
			sSql = "insert into fichas (";
			sSql += "serial, level0, level1, level2, name0, name1, name2, evento";
			sSql += ", lugar, fechano, fechames, fechadia, muertos, heridos, desaparece, afectados";
			sSql += ", vivdest, vivafec, otros, fuentes, valorloc, valorus, fechapor, fechafec";
			sSql += ", hay_muertos, hay_heridos, hay_deasparece, hay_afectados, hay_vivdest, hay_vivafec";
			sSql += ", hay_otros, socorro, salud, educacion, agropecuario, industrias, acueducto";
			sSql += ", alcantarillado, energia, comunicaciones, causa, descausa, transporte, magnitud2";
			sSql += ", nhospitales, nescuelas, nhectareas, cabezas, kmvias, duracion, damnificados";
			sSql += ", evacuados, hay_damnificados, hay_evacuados, hay_reubicados, reubicados";
			sSql += ",  glide, defaultab, approved, latitude, longitude, uu_id, di_comments)";
			sSql += "VALUES (?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?, ?, " +
					        "?, ?, ?, ?, ?, ?, ?)";
			PreparedStatement pstmt = con.prepareStatement(sSql);

			
			if (uu_id.length()==0){
				// GENERATES THE GLOBAL UNIVERSAL UNIQUE ID
				UUID uuid = UUID.randomUUID(); 
				uu_id = uuid.toString(); 
			}
			

			checkLengths();
			
			pstmt.setString(f++, serial);

			if (level0 == null || level0.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level0);

			if (level1 == null || level1.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level1);

			if (level2 == null || level2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level2);

			if (name0 == null || name0.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name0);

			if (name1 == null || name1.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name1);

			if (name2 == null || name2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name2);

			if (evento == null || evento.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, evento);

			if (lugar == null || lugar.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, lugar);
			pstmt.setInt(f++, fechano);
			pstmt.setInt(f++, fechames);
			pstmt.setInt(f++, fechadia);
			pstmt.setInt(f++, muertos);
			pstmt.setInt(f++, heridos);
			pstmt.setInt(f++, desaparece);
			pstmt.setInt(f++, afectados);
			pstmt.setInt(f++, vivdest);
			pstmt.setInt(f++, vivafec);

			if (otros == null || otros.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, otros);
			if (fuentes == null || fuentes.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fuentes);
			pstmt.setDouble(f++, valorloc);
			pstmt.setDouble(f++, valorus);

			if (fechapor == null || fechapor.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fechapor);

			if (fechafec == null || fechafec.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fechafec);
			pstmt.setInt(f++, hay_muertos);
			pstmt.setInt(f++, hay_heridos);
			pstmt.setInt(f++, hay_deasparece);
			pstmt.setInt(f++, hay_afectados);
			pstmt.setInt(f++, hay_vivdest);
			pstmt.setInt(f++, hay_vivafec);
			pstmt.setInt(f++, hay_otros);
			pstmt.setInt(f++, socorro);
			pstmt.setInt(f++, salud);
			pstmt.setInt(f++, educacion);
			pstmt.setInt(f++, agropecuario);
			pstmt.setInt(f++, industrias);
			pstmt.setInt(f++, acueducto);
			pstmt.setInt(f++, alcantarillado);
			pstmt.setInt(f++, energia);
			pstmt.setInt(f++, comunicaciones);

			if (causa == null || causa.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, causa);

			if (descausa == null || descausa.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, descausa);
			pstmt.setInt(f++, transporte);

			if (magnitud2 == null || magnitud2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, magnitud2);
			pstmt.setInt(f++, nhospitales);
			pstmt.setInt(f++, nescuelas);
			pstmt.setDouble(f++, nhectareas);
			pstmt.setInt(f++, cabezas);
			pstmt.setDouble(f++, kmvias);

			pstmt.setInt(f++, duracion);
			pstmt.setInt(f++, damnificados);
			pstmt.setInt(f++, evacuados);
			pstmt.setInt(f++, hay_damnificados);
			pstmt.setInt(f++, hay_evacuados);
			pstmt.setInt(f++, hay_reubicados);
			pstmt.setInt(f++, reubicados);

			// NOT included, is AUTONUMBER pstmt.setInt(f++, clave);

			if (glide == null || glide.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, glide);
			
			if (defaultab == 0)
				pstmt.setNull(f++, Types.INTEGER);
			else
				pstmt.setInt(f++, defaultab);
			
			pstmt.setInt(f++, approved);			
			pstmt.setDouble(f++, latitude);
			pstmt.setDouble(f++, longitude);
			
			pstmt.setString(f++, uu_id);
				
			if (di_comments==null || di_comments.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else
				pstmt.setString(f++, di_comments);

			int nrows = pstmt.executeUpdate();
			// force commit here ??
		    // con.commit();  
		    pstmt.close();
		    
		    // get the new key generated
			pstmt = con.prepareStatement("select max(clave) as maxclave_ from fichas where uu_id=?");
			pstmt.setString(1, uu_id);
			rset = pstmt.executeQuery();
			if (rset.next())
		      {
		        // gets the new key
		        clave = rset.getInt("maxclave_");
		        // and takes care of updating the hashtable, just the required piece...
		        asFieldNames.put("clave", String.valueOf(clave));
		      }
	        try
	        {
	        	rset.close();
	        	pstmt.close();
	        }
			catch (Exception erst)
			{
			// nothing for now
			}
			

			// releases the statement object
			lastError = ""; // "NO ERROR. sql="+sSql;
			return nrows;
		} catch (Exception ex) {
			//Trap and report SQL errors
			System.out.println("[DI9] ERROR (adding webObject): DATACARD "+ex.toString());
			lastError = "<!-- Error adding webObject: " + ex.toString() + " : " + sSql + " -->";
		    try{
		    	pstmt.close();
		    }
		    catch(Exception e)
		    {
		    	// do nothing for now
		    }
			return -1;
		}
	}

	//--------------------------------------------------------------------------------
	// updates an existing object in the database
	//--------------------------------------------------------------------------------
  public int updateWebObject(Connection con)
    {
		try {
			// SQL_UPDATE
			int f=1;
			sSql = "UPDATE fichas SET ";
			sSql += "serial = ?";
			sSql += ", level0 = ?";
			sSql += ", level1 = ?";
			sSql += ", level2 = ?";
			sSql += ", name0 = ?";
			sSql += ", name1 = ?";
			sSql += ", name2 = ?";
			sSql += ", evento = ?";
			sSql += ", lugar = ?";
			sSql += ", fechano = ?";
			sSql += ", fechames = ?";
			sSql += ", fechadia = ?";
			sSql += ", muertos = ?";
			sSql += ", heridos = ?";
			sSql += ", desaparece = ?";
			sSql += ", afectados = ?";
			sSql += ", vivdest = ?";
			sSql += ", vivafec = ?";
			sSql += ", otros = ?";
			sSql += ", fuentes = ?";
			sSql += ", valorloc = ?";
			sSql += ", valorus = ?";
			sSql += ", fechapor = ?";
			sSql += ", fechafec = ?";
			sSql += ", hay_muertos = ?";
			sSql += ", hay_heridos = ?";
			sSql += ", hay_deasparece = ?";
			sSql += ", hay_afectados = ?";
			sSql += ", hay_vivdest = ?";
			sSql += ", hay_vivafec = ?";
			sSql += ", hay_otros = ?";
			sSql += ", socorro = ?";
			sSql += ", salud = ?";
			sSql += ", educacion = ?";
			sSql += ", agropecuario = ?";
			sSql += ", industrias = ?";
			sSql += ", acueducto = ?";
			sSql += ", alcantarillado = ?";
			sSql += ", energia = ?";
			sSql += ", comunicaciones = ?";
			sSql += ", causa = ?";
			sSql += ", descausa = ?";
			sSql += ", transporte = ?";
			sSql += ", magnitud2 = ?";
			sSql += ", nhospitales = ?";
			sSql += ", nescuelas = ?";
			sSql += ", nhectareas = ?";
			sSql += ", cabezas = ?";
			sSql += ", kmvias = ?";
			sSql += ", duracion = ?";
			sSql += ", damnificados = ?";
			sSql += ", evacuados = ?";
			sSql += ", hay_damnificados = ?";
			sSql += ", hay_evacuados = ?";
			sSql += ", hay_reubicados = ?";
			sSql += ", reubicados = ?";
			sSql += ", glide = ?";
			sSql += ", defaultab = ?";
			sSql += ", approved = ?";
			sSql += ", latitude = ?";
			sSql += ", longitude = ?";
			sSql += ", uu_id = ?";
			sSql += ", di_comments = ?";
			sSql += " WHERE (clave = ?)";
			pstmt = con.prepareStatement(sSql);


			if (serial == null || serial.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, serial);

			if (level0 == null || level0.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level0);

			if (level1 == null || level1.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level1);

			if (level2 == null || level2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, level2);

			if (name0 == null || name0.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name0);

			if (name1 == null || name1.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name1);

			if (name2 == null || name2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, name2);

			if (evento == null || evento.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, evento);

			if (lugar == null || lugar.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, lugar);
			pstmt.setInt(f++, fechano);
			pstmt.setInt(f++, fechames);
			pstmt.setInt(f++, fechadia);
			pstmt.setInt(f++, muertos);
			pstmt.setInt(f++, heridos);
			pstmt.setInt(f++, desaparece);
			pstmt.setInt(f++, afectados);
			pstmt.setInt(f++, vivdest);
			pstmt.setInt(f++, vivafec);

			if (otros == null || otros.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, otros);
			if (fuentes == null || fuentes.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fuentes);
			pstmt.setDouble(f++, valorloc);
			pstmt.setDouble(f++, valorus);

			if (fechapor == null || fechapor.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fechapor);

			if (fechafec == null || fechafec.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, fechafec);
			pstmt.setInt(f++, hay_muertos);
			pstmt.setInt(f++, hay_heridos);
			pstmt.setInt(f++, hay_deasparece);
			pstmt.setInt(f++, hay_afectados);
			pstmt.setInt(f++, hay_vivdest);
			pstmt.setInt(f++, hay_vivafec);
			pstmt.setInt(f++, hay_otros);
			pstmt.setInt(f++, socorro);
			pstmt.setInt(f++, salud);
			pstmt.setInt(f++, educacion);
			pstmt.setInt(f++, agropecuario);
			pstmt.setInt(f++, industrias);
			pstmt.setInt(f++, acueducto);
			pstmt.setInt(f++, alcantarillado);
			pstmt.setInt(f++, energia);
			pstmt.setInt(f++, comunicaciones);

			if (causa == null || causa.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, causa);

			if (descausa == null || descausa.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, descausa);
			pstmt.setInt(f++, transporte);

			if (magnitud2 == null || magnitud2.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, magnitud2);

			pstmt.setInt(f++, nhospitales);
			pstmt.setInt(f++, nescuelas);
			pstmt.setDouble(f++, nhectareas);
			pstmt.setInt(f++, cabezas);
			pstmt.setDouble(f++, kmvias);

			pstmt.setInt(f++, duracion);
			pstmt.setInt(f++, damnificados);
			pstmt.setInt(f++, evacuados);
			pstmt.setInt(f++, hay_damnificados);
			pstmt.setInt(f++, hay_evacuados);
			pstmt.setInt(f++, hay_reubicados);
			pstmt.setInt(f++, reubicados);

			if (glide == null || glide.length() == 0)
				pstmt.setNull(f++, Types.VARCHAR);
			else
				pstmt.setString(f++, glide);
			
			pstmt.setInt(f++, defaultab);
			pstmt.setInt(f++, approved);
			pstmt.setDouble(f++, latitude);
			pstmt.setDouble(f++, longitude);
			if (uu_id==null || uu_id.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else 
				pstmt.setString(f++, uu_id);
			if (di_comments==null || di_comments.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else 
				pstmt.setString(f++, di_comments);

			pstmt.setInt(f++, clave);
			int nrows = pstmt.executeUpdate();			
			// releases the statement object
			pstmt.close();
			lastError = ""; // "NO ERROR. sql="+sSql;
			return nrows;
		} catch (Exception ex) {
			//Trap and report SQL errors
			try{
		    	pstmt.close();
		    }
		    catch(Exception e)
		    {
		    	// do nothing for now
		    }
			lastError = "<!-- Error updating webObject: " + ex.toString() + " : " + sSql + " -->";
		}

		return -1;
	}

	//-------------------------------------------------------------------------------
	// deletes an existing object in the database
	//--------------------------------------------------------------------------------
	public int deleteWebObject(Connection con) {

		try {
			// SQL_DELETE
			int f=1;
			sSql = "DELETE FROM fichas";
			sSql += " WHERE (clave = ?)";
			pstmt = con.prepareStatement(sSql);

			pstmt.setInt(f++, clave);
			int nrows = pstmt.executeUpdate();			// releases the statement object
			pstmt.close();
			lastError = ""; // "NO ERROR. sql="+sSql;
return nrows;
		} catch (Exception ex) {
			//Trap and report SQL errors
			try{
		    	pstmt.close();
		    }
		    catch(Exception e)
		    {
		    	// do nothing for now
		    }
			lastError = "<!-- Error deleting webObject: " + ex.toString() + " : " + sSql + " -->";
		}
		return -1;
	}
}

/*    HTML TEMPLATE
<table border=0 cellspacing=0 cellpadding=0>
<tr><td>serial:</td><td>  <INPUT type='TEXT' size='7' maxlength='6' name='serial' VALUE="<%=beanName.serial%>"></td></tr>
<tr><td>level0:</td><td>  <INPUT type='TEXT' size='16' maxlength='15' name='level0' VALUE="<%=beanName.level0%>"></td></tr>
<tr><td>level1:</td><td>  <INPUT type='TEXT' size='16' maxlength='15' name='level1' VALUE="<%=beanName.level1%>"></td></tr>
<tr><td>level2:</td><td>  <INPUT type='TEXT' size='16' maxlength='15' name='level2' VALUE="<%=beanName.level2%>"></td></tr>
<tr><td>name0:</td><td>  <INPUT type='TEXT' size='31' maxlength='30' name='name0' VALUE="<%=beanName.name0%>"></td></tr>
<tr><td>name1:</td><td>  <INPUT type='TEXT' size='31' maxlength='30' name='name1' VALUE="<%=beanName.name1%>"></td></tr>
<tr><td>name2:</td><td>  <INPUT type='TEXT' size='31' maxlength='30' name='name2' VALUE="<%=beanName.name2%>"></td></tr>
<tr><td>evento:</td><td>  <INPUT type='TEXT' size='16' maxlength='15' name='evento' VALUE="<%=beanName.evento%>"></td></tr>
<tr><td>lugar:</td><td>  <INPUT type='TEXT' size='50' maxlength='60' name='lugar' VALUE="<%=beanName.lugar%>"></td></tr>
<tr><td>fechano:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='fechano' VALUE="<%=beanName.fechano%>"></td></tr>
<tr><td>fechames:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='fechames' VALUE="<%=beanName.fechames%>"></td></tr>
<tr><td>fechadia:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='fechadia' VALUE="<%=beanName.fechadia%>"></td></tr>
<tr><td>muertos:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='muertos' VALUE="<%=beanName.muertos%>"></td></tr>
<tr><td>heridos:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='heridos' VALUE="<%=beanName.heridos%>"></td></tr>
<tr><td>desaparece:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='desaparece' VALUE="<%=beanName.desaparece%>"></td></tr>
<tr><td>afectados:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='afectados' VALUE="<%=beanName.afectados%>"></td></tr>
<tr><td>vivdest:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='vivdest' VALUE="<%=beanName.vivdest%>"></td></tr>
<tr><td>vivafec:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='vivafec' VALUE="<%=beanName.vivafec%>"></td></tr>
<tr><td>otros:</td><td>  <INPUT type='TEXT' size='50' maxlength='60' name='otros' VALUE="<%=beanName.otros%>"></td></tr>
<tr><td>fuentes:</td><td>  <INPUT type='TEXT' size='41' maxlength='40' name='fuentes' VALUE="<%=beanName.fuentes%>"></td></tr>
<tr><td>valorloc:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='valorloc' VALUE="<%=beanName.valorloc%>"></td></tr>
<tr><td>valorus:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='valorus' VALUE="<%=beanName.valorus%>"></td></tr>
<tr><td>fechapor:</td><td>  <INPUT type='TEXT' size='13' maxlength='12' name='fechapor' VALUE="<%=beanName.fechapor%>"></td></tr>
<tr><td>fechafec:</td><td>  <INPUT type='TEXT' size='13' maxlength='12' name='fechafec' VALUE="<%=beanName.fechafec%>"></td></tr>
<tr><td>hay_muertos:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_muertos' VALUE="<%=beanName.hay_muertos%>"></td></tr>
<tr><td>hay_heridos:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_heridos' VALUE="<%=beanName.hay_heridos%>"></td></tr>
<tr><td>hay_deasparece:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_deasparece' VALUE="<%=beanName.hay_deasparece%>"></td></tr>
<tr><td>hay_afectados:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_afectados' VALUE="<%=beanName.hay_afectados%>"></td></tr>
<tr><td>hay_vivdest:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_vivdest' VALUE="<%=beanName.hay_vivdest%>"></td></tr>
<tr><td>hay_vivafec:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_vivafec' VALUE="<%=beanName.hay_vivafec%>"></td></tr>
<tr><td>hay_otros:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_otros' VALUE="<%=beanName.hay_otros%>"></td></tr>
<tr><td>socorro:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='socorro' VALUE="<%=beanName.socorro%>"></td></tr>
<tr><td>salud:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='salud' VALUE="<%=beanName.salud%>"></td></tr>
<tr><td>educacion:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='educacion' VALUE="<%=beanName.educacion%>"></td></tr>
<tr><td>agropecuario:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='agropecuario' VALUE="<%=beanName.agropecuario%>"></td></tr>
<tr><td>industrias:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='industrias' VALUE="<%=beanName.industrias%>"></td></tr>
<tr><td>acueducto:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='acueducto' VALUE="<%=beanName.acueducto%>"></td></tr>
<tr><td>alcantarillado:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='alcantarillado' VALUE="<%=beanName.alcantarillado%>"></td></tr>
<tr><td>energia:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='energia' VALUE="<%=beanName.energia%>"></td></tr>
<tr><td>comunicaciones:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='comunicaciones' VALUE="<%=beanName.comunicaciones%>"></td></tr>
<tr><td>causa:</td><td>  <INPUT type='TEXT' size='26' maxlength='25' name='causa' VALUE="<%=beanName.causa%>"></td></tr>
<tr><td>descausa:</td><td>  <INPUT type='TEXT' size='50' maxlength='60' name='descausa' VALUE="<%=beanName.descausa%>"></td></tr>
<tr><td>transporte:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='transporte' VALUE="<%=beanName.transporte%>"></td></tr>
<tr><td>magnitud2:</td><td>  <INPUT type='TEXT' size='26' maxlength='25' name='magnitud2' VALUE="<%=beanName.magnitud2%>"></td></tr>
<tr><td>nhospitales:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='nhospitales' VALUE="<%=beanName.nhospitales%>"></td></tr>
<tr><td>nescuelas:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='nescuelas' VALUE="<%=beanName.nescuelas%>"></td></tr>
<tr><td>nhectareas:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='nhectareas' VALUE="<%=beanName.nhectareas%>"></td></tr>
<tr><td>cabezas:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='cabezas' VALUE="<%=beanName.cabezas%>"></td></tr>
<tr><td>kmvias:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='kmvias' VALUE="<%=beanName.kmvias%>"></td></tr>
<tr><td>duracion:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='duracion' VALUE="<%=beanName.duracion%>"></td></tr>
<tr><td>damnificados:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='damnificados' VALUE="<%=beanName.damnificados%>"></td></tr>
<tr><td>evacuados:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='evacuados' VALUE="<%=beanName.evacuados%>"></td></tr>
<tr><td>hay_damnificados:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_damnificados' VALUE="<%=beanName.hay_damnificados%>"></td></tr>
<tr><td>hay_evacuados:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_evacuados' VALUE="<%=beanName.hay_evacuados%>"></td></tr>
<tr><td>hay_reubicados:</td><td>  <INPUT type='TEXT' size='5' maxlength='6' name='hay_reubicados' VALUE="<%=beanName.hay_reubicados%>"></td></tr>
<tr><td>reubicados:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='reubicados' VALUE="<%=beanName.reubicados%>"></td></tr>
<tr><td>clave:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='clave' VALUE="<%=beanName.clave%>"></td></tr>
<tr><td>glide:</td><td>  <INPUT type='TEXT' size='31' maxlength='30' name='glide' VALUE="<%=beanName.glide%>"></td></tr>
<tr><td>defaultab:</td><td>  <INPUT type='TEXT' size='5' maxlength='22' name='defaultab' VALUE="<%=beanName.defaultab%>"></td></tr>
<tr><td>approved:</td><td>  <INPUT type='TEXT' size='5' maxlength='22' name='approved' VALUE="<%=beanName.approved%>"></td></tr>
<tr><td>latitude:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='latitude' VALUE="<%=beanName.latitude%>"></td></tr>
<tr><td>longitude:</td><td>  <INPUT type='TEXT' size='15' maxlength='22' name='longitude' VALUE="<%=beanName.longitude%>"></td></tr>
</table>
END HTML TEMPLATE */
