//PACKAGE NAME
package org.lared.desinventar.webobject;

import java.io.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import java.text.*;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.*;


//CLASS NAME
// generated by WebObjectGenerator...
public class MetadataIndicator extends webObject
{
//    public int dbType=Sys.iDatabaseType;	

	// DATA MEMBERS OF THE CLASS. THEY ARE EXACT MAPPING OF DB. RECORD.
	public 	int    indicator_key;
	public 	String indicator_code;
	public 	String indicator_description;

	/**
	* creates a hash table with field values of the data members
	*
	*/

	public void updateHashTable() {
		// FIELD NAMES VECTOR
		asFieldNames.put("indicator_key", String.valueOf(indicator_key));
		asFieldNames.put("indicator_code", indicator_code);
		asFieldNames.put("indicator_description", indicator_description);

	}

	/**
	* update data members with values stored in hash table
	*
	*/

	public void updateMembersFromHashTable() {
		// REVERSE FIELD NAMES VECTOR
		setIndicator_key((String)asFieldNames.get("indicator_key"));
		setIndicator_code((String)asFieldNames.get("indicator_code"));
		setIndicator_description((String)asFieldNames.get("indicator_description"));

	}
	/**
	* constructor of the class. it initialises the object variables
	*
	*/

	// CONSTRUCTOR
	public void init() {
		lastError="No errors detected";
		indicator_key = 0;
		indicator_code = "";
		indicator_description = "";
		updateHashTable();
	}

	public MetadataIndicator() {
		super("MetadataIndicator object");
		init();
	}
//--------------------------------------------------------------------------------
// getter and setter methods of the elements of the class
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'indicator_key'
	public String getIndicator_key() {
		return Integer.toString(indicator_key);
	}

	public void setIndicator_key(String sParameter) {
		indicator_key = extendedParseInt(sParameter);
	}

	public void setIndicator_key(int sParameter) {
		indicator_key = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'indicator_code'
	public String getIndicator_code() {
		return indicator_code;
	}

	public void setIndicator_code(String sParameter) {
		indicator_code = sParameter;
	}
//--------------------------------------------------------------------------------

//--------------------------------------------------------------------------------
// Access methods for database field 'indicator_description'
	public String getIndicator_description() {
		return indicator_description;
	}

	public void setIndicator_description(String sParameter) {
		indicator_description = sParameter;
	}
//--------------------------------------------------------------------------------


	//----------------------------------------------------------------
	// Operational methods any webObject must have. Abstract class
	// provides templates and default behaviour (return error)
	//----------------------------------------------------------------

	/**
	* retrieves object info from HTML form fields
	*
	*/
	public int getForm(HttpServletRequest req, HttpServletResponse resp, Connection con) {

		// GET_FORM()
		setIndicator_key(req.getParameter(assignName("indicator_key")));
		setIndicator_code(not_null_safe(req.getParameter(assignName("indicator_code"))));
		setIndicator_description(not_null_safe(req.getParameter(assignName("indicator_description"))));

		updateHashTable();
		return 0;
	}

	/**
	* retrieves object info from HTML form fields
	*
	*/
	public int getForm(ServletRequest req, ServletResponse resp, Connection con) {

		// GET_FORM()
		setIndicator_key(req.getParameter(assignName("indicator_key")));
		setIndicator_code(not_null_safe(req.getParameter(assignName("indicator_code"))));
		setIndicator_description(not_null_safe(req.getParameter(assignName("indicator_description"))));

		this.checkLengths();
		
		updateHashTable();
		return 0;
	}


	/**
	* loads an object from a record read from database
	*
	*/
	public void loadWebObject(ResultSet rset) {
		try {
			// SQL_LOAD

			try {
				indicator_key = rset.getInt("indicator_key");

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field indicator_key -->";
				System.out.println(ex.toString());
			}

			try {
				indicator_code = not_null(rset.getString("indicator_code"));

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field indicator_code -->";
				System.out.println(ex.toString());
			}

			try {
				indicator_description = not_null(rset.getString("indicator_description"));

			} catch (Exception ex) {
				lastError = "<-- error attempting to access field indicator_description -->";
				System.out.println(ex.toString());
			}

		} catch (Exception e) {
			lastError = "<!-- Error loading WebObject: " + e.toString() + " : " + sSql + " -->";
		}
		updateHashTable();
	}

	/**
	* reads an object from the database
	*
	*/
	public int getWebObject(Connection con) 
	{
		int nrows = 0;
		try {		
			// SQL_GET
			int f=1;
			sSql = "SELECT * FROM metadata_indicator";
			sSql += " WHERE (indicator_key = ?)";
			pstmt = con.prepareStatement(sSql);

				pstmt.setInt(f++, indicator_key);


			rset = pstmt.executeQuery();
			if (rset.next()) {
				loadWebObject(rset);
				nrows = 1;				
			}			
			// releases the statement object
			rset.close();
			pstmt.close();
			lastError = ""; // "NO ERROR. sql="+sSql;
		} catch (Exception ex) {
			//Trap and report SQL errors
			lastError = "<!-- Error getting webObject: " + ex.toString() + " : " + sSql	+ " -->";
			nrows = -1;
		}
		finally {
			// releases the statement object
			try { pstmt.close(); } catch (Exception ignrd) {}
		}

		return nrows;
	}



	/**
	* checks the lengths of strings are <= to what is defined in the database
	*
	*/
	public void checkLengths()
    {
		// CHECK_LENGTHS
		if (indicator_code.length()>10)
			indicator_code=indicator_code.substring(0,10);
		if (indicator_description.length()>250)
			indicator_description=indicator_description.substring(0,250);
    }

	/**
	* adds a new object to the database
	*
	*/
	public int addWebObject(Connection con)
    {
		int nrows = 0;
		try {
			// SQL_INSERT
			int f=1;
			sSql = "insert into metadata_indicator (";
			sSql += "indicator_key, indicator_code, indicator_description)";
			sSql += "VALUES (?, ?, ?)";
			pstmt = con.prepareStatement(sSql);

				pstmt.setInt(f++, indicator_key);
			if (indicator_code==null || indicator_code.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else
				pstmt.setString(f++, indicator_code);
			if (indicator_description==null || indicator_description.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else
				pstmt.setString(f++, indicator_description);


			nrows = pstmt.executeUpdate();
			lastError = ""; // "NO ERROR. sql="+sSql;
		} catch (Exception ex) {
			//Trap and report SQL errors
			System.out.println("ERROR (adding web object): "+ex.toString());
			lastError = "<!-- Error adding webObject: " + ex.toString() + " : " + sSql + " -->";
			nrows=-1;
		}
		finally {
			// releases the statement object
			try { pstmt.close(); } catch (Exception ignrd) {}
		}
		return nrows;		
	}

  	/**
  	* updates an existing object in the database
  	*
  	*/
  	public int updateWebObject(Connection con)
    {
		int nrows = 0;
		try {
			// SQL_UPDATE
			int f=1;
			sSql = "UPDATE metadata_indicator SET ";
			sSql += "indicator_code = ?";
			sSql += ", indicator_description = ?";
			sSql += " WHERE (indicator_key = ?)";
			pstmt = con.prepareStatement(sSql);

			if (indicator_code==null || indicator_code.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else 
				pstmt.setString(f++, indicator_code);
			if (indicator_description==null || indicator_description.length()==0)
				pstmt.setNull(f++, java.sql.Types.VARCHAR);
			else 
				pstmt.setString(f++, indicator_description);


				pstmt.setInt(f++, indicator_key);


			nrows = pstmt.executeUpdate();
			lastError = ""; // "NO ERROR. sql="+sSql;
		} catch (Exception ex) {
			//Trap and report SQL errors
			lastError = "<!-- Error updating webObject: " + ex.toString() + " : " + sSql + " -->";
			nrows=-1;
		}
		finally {
			// releases the statement object
			try { pstmt.close(); } catch (Exception ignrd) {}
		}
		return nrows;		
	}

	/**
	* deletes an existing object in the database
	*
	*/
	public int deleteWebObject(Connection con) 
	{
		int nrows = 0;
		try {
			// SQL_DELETE
			int f=1;
			sSql = "DELETE FROM metadata_indicator";
			sSql += " WHERE (indicator_key = ?)";
			pstmt = con.prepareStatement(sSql);

				pstmt.setInt(f++, indicator_key);


			nrows = pstmt.executeUpdate();
			lastError = ""; // "NO ERROR. sql="+sSql;
		} catch (Exception ex) {
			//Trap and report SQL errors
			lastError = "<!-- Error deleting webObject: " + ex.toString() + " : " + sSql + " -->";
			nrows=-1;
		}
		finally {
			// releases the statement object
			try { pstmt.close(); } catch (Exception ignrd) {}
		}
		return nrows;		
	}
}

/*    HTML TEMPLATE
<table border=0 cellspacing=0 cellpadding=0>
<tr><td>indicator_key:</td><td>  <INPUT type='TEXT' size='5' maxlength='11' name='indicator_key' VALUE="<%=beanName.indicator_key%>"></td></tr>
<tr><td>indicator_code:</td><td>  <INPUT type='TEXT' size='11' maxlength='10' name='indicator_code' VALUE="<%=beanName.indicator_code%>"></td></tr>
<tr><td>indicator_description:</td><td>  <INPUT type='TEXT' size='50' maxlength='250' name='indicator_description' VALUE="<%=beanName.indicator_description%>"></td></tr>
</table>
END HTML TEMPLATE */
